services:
    aws:
        class: 'Aws\Sdk'
        arguments:
            - { version: 'latest' }

    aws.authenticator:
        class: 'Hal\Core\AWS\AWSAuthenticator'
        arguments:
            - '@logger'
            - '@aws.credential_provider'
            - '@aws'

    aws.credential_provider:
        class: 'Hal\Core\AWS\CredentialProvider'
        arguments:
            - '@logger'
            - '@encryption'
            - '@doctrine.em'
            - '@aws'
            - '%aws.use_host_credentials%'
        calls:
            - ['setHostCredentials', ['@aws.host_sdk_credential_provider']]

    aws.host_sdk_credential_provider:
        class: 'Aws\Credentials\CredentialProvider'
        factory: ['Aws\Credentials\CredentialProvider', 'ini']
        arguments:
            - null
            - '%aws.host_credentials_path%'
