services:
    ####################################################################################################################
    # GITHUB
    ####################################################################################################################

    github:
        class: 'Hal\UI\Service\GitHubService'
        arguments:
            - '@github.sdk.repos'
            - '@github.sdk.repo_commits'
            - '@github.sdk.git_references'
            - '@github.sdk.git_commits'
            - '@github.sdk.pull_requests'
            - '@github.sdk.users'
            - '@github.sdk.org_members'
            - '@github.pager'

    ####################################################################################################################
    # GITHUB AUTH
    ####################################################################################################################

    # github.oauth:
    #     class: 'Hal\UI\Github\OAuthHandler'
    #     arguments:
    #         - '@github.oauth.guzzle'
    #         - '%github.baseurl.api%'
    #         - '%github.baseurl.site%'
    #         - '%github.app.id%'
    #         - '%github.app.secret%'
    #         - '@json'

    # github.oauth.guzzle:
    #     class: 'GuzzleHttp\Client'

    ####################################################################################################################
    # GITHUB SDK
    ####################################################################################################################

    github.url_builder:
        class: 'Hal\UI\Github\GitHubURLBuilder'
        arguments: ['@github', '%github.baseurl.site%']

    github.client:
        class: 'Hal\UI\Github\EnterpriseClient'
        arguments:
            - '@github.http.builder'
            - null
            - '%github.baseurl.site%'
        configurator: ['@github.client.configurator', configure]
        calls:
            - ['authenticate', ['%github.token%', null, 'http_token']]

    github.client.configurator:
        class: 'Hal\UI\Github\GithubClientConfigurator'
        arguments: ['@github.http_cache.plugin', '@github.http.builder']

    github.http.builder:
        class: 'Github\HttpClient\Builder'

    github.http_cache.plugin:
        class: 'Hal\UI\Github\MCPCachePlugin'
        arguments:
            - '@cache.github'
            - '@github.http_cache.http_stream_factory'
            -
                respect_cache_headers: false
                default_ttl: '%cache.github.default.ttl%'
            - '%cache.github.short.ttl%'

    github.http_cache.http_stream_factory:
        class: 'Http\Message\StreamFactory\GuzzleStreamFactory'

    github.pager:
        class: 'Github\ResultPager'
        arguments: ['@github.client']

    github.sdk.pull_requests:
        class: 'Github\Api\PullRequest'
        arguments: ['@github.client']
    github.sdk.git_references:
        class: 'Github\Api\GitData\References'
        arguments: ['@github.client']
    github.sdk.git_commits:
        class: 'Github\Api\GitData\Commits'
        arguments: ['@github.client']
    github.sdk.repos:
        class: 'Github\Api\Repo'
        arguments: ['@github.client']
    github.sdk.repo_commits:
        class: 'Github\Api\Repository\Commits'
        arguments: ['@github.client']
    github.sdk.users:
        class: 'Github\Api\User'
        arguments: ['@github.client']
    github.sdk.org_members:
        class: 'Github\Api\Organization\Members'
        arguments: ['@github.client']
