services:
    ####################################################################################################################
    # AUTHORIZATIONS
    ####################################################################################################################

    service.authorization:
        class: 'Hal\UI\Security\AuthorizationService'
        arguments:
            - '@doctrine.em'
            - '@json'
        calls:
            - ['setCache', ['@cache']]
            - ['setCacheTTL', ['%cache.permissions.ttl%']]

    service.authorization_hydrator:
        class: 'Hal\UI\Security\AuthorizationHydrator'
        arguments: ['@doctrine.em']

    ####################################################################################################################
    # CRYPTO
    ####################################################################################################################

    encryption:
        class: 'Hal\Core\Crypto\Encryption'
        factory: ['@encryption.factory', 'getCrypto']

    encryption.factory:
        class: 'Hal\Core\Crypto\CryptoFilesystemFactory'
        arguments: ['%encrypter.secret.path%']

    # dummy services - to not break pages not updated to core-3 yet
    decrypter:
        parent: 'encryption'
    encrypter:
        parent: 'encryption'
