services:
    ####################################################################################################################
    # authentications
    ####################################################################################################################

    auth:
        class: 'Hal\UI\Security\Auth'
        arguments:
            - '@service.oauth_provider.factory'
            -
                ldap: '@auth.ldap'
                internal: '@auth.internal'
                ghe: '@auth.github_enterprise'
                gh: '@auth.github'

    auth.internal:
        class: 'Hal\UI\Security\UserAuthentication\InternalAuth'
        arguments: ['@doctrine.em']

    auth.ldap:
        class: 'Hal\UI\Security\UserAuthentication\LdapAuth'
        arguments:
            - '@doctrine.em'
            - '%ldap.query_restriction%'
            - '%ldap.unique_attribute%'

    auth.github_enterprise:
        class: 'Hal\UI\Security\UserAuthentication\OAuth'
        arguments:
            - '@service.user_identity'
            - '@service.oauth_provider.factory'

    auth.github:
        class: 'Hal\UI\Security\UserAuthentication\OAuth'
        arguments:
            - '@service.user_identity'
            - '@service.oauth_provider.factory'

    ####################################################################################################################
    # authorizations
    ####################################################################################################################

    service.authorization:
        class: 'Hal\UI\Security\AuthorizationService'
        arguments:
            - '@doctrine.em'
            - '@json'
        calls:
            - ['setCache', ['@cache']]
            - ['setCacheTTL', ['%cache.permissions.ttl%']]

    service.authorization_hydrator:
        class: 'Hal\UI\Security\AuthorizationHydrator'
        arguments: ['@doctrine.em']

    service.oauth_provider.factory:
        class: 'Hal\UI\Security\OAuthProviderFactory'

    ####################################################################################################################
    # forms
    ####################################################################################################################

    csrf:
        class: 'Hal\UI\Security\CSRFManager'
        arguments: ['@clock']

    user_session.handler:
        class: 'Hal\UI\Security\UserSessionHandler'
        arguments:
            - '@doctrine.em'
            - '@service.authorization'
            - '@clock'

    ####################################################################################################################
    # crypto
    ####################################################################################################################

    encryption:
        class: 'Hal\Core\Crypto\Encryption'
        factory: ['@encryption.factory', 'getCrypto']

    encryption.factory:
        class: 'Hal\Core\Crypto\CryptoFilesystemFactory'
        arguments: ['%encrypter.secret.path%']

    # dummy services - to not break pages not updated to core-3 yet
    decrypter:
        parent: 'encryption'
    encrypter:
        parent: 'encryption'
