services:
    ####################################################################################################################
    # authentications
    ####################################################################################################################

    auth:
        class: 'Hal\UI\Security\Auth'
        arguments:
            -
                ldap: '@auth.ldap'
                internal: '@auth.internal'

    auth.internal:
        class: 'Hal\UI\Security\UserAuthentication\InternalAuth'
        arguments: ['@doctrine.em']

    auth.ldap:
        class: 'Hal\UI\Security\UserAuthentication\LdapAuth'
        arguments: ['@doctrine.em']

    ####################################################################################################################
    # authorizations
    ####################################################################################################################

    service.authorization:
        class: 'Hal\UI\Security\AuthorizationService'
        arguments:
            - '@doctrine.em'
            - '@json'
        calls:
            - ['setCache', ['@cache']]
            - ['setCacheTTL', ['%cache.permissions.ttl%']]

    service.authorization_hydrator:
        class: 'Hal\UI\Security\AuthorizationHydrator'
        arguments: ['@doctrine.em']

    ####################################################################################################################
    # forms
    ####################################################################################################################

    csrf:
        class: 'Hal\UI\Security\CSRFManager'
        arguments: ['@clock']

    ####################################################################################################################
    # crypto
    ####################################################################################################################

    encryption:
        class: 'Hal\Core\Crypto\Encryption'
        factory: ['@encryption.factory', 'getCrypto']

    encryption.factory:
        class: 'Hal\Core\Crypto\CryptoFilesystemFactory'
        arguments: ['%encrypter.secret.path%']

    # dummy services - to not break pages not updated to core-3 yet
    decrypter:
        parent: 'encryption'
    encrypter:
        parent: 'encryption'
