services:
    ####################################################################################################################
    # authentications
    ####################################################################################################################

    auth:
        class: 'Hal\UI\Security\Auth'
        arguments:
            -
                ldap: '@auth.ldap'
                internal: '@auth.internal'
                ghe: '@auth.github_enterprise'
                gh: '@auth.github'

    auth.internal:
        class: 'Hal\UI\Security\UserAuthentication\InternalAuth'
        arguments: ['@doctrine.em']

    auth.ldap:
        class: 'Hal\UI\Security\UserAuthentication\LdapAuth'
        arguments:
            - '@doctrine.em'
            - '%ldap.query_restriction%'
            - '%ldap.unique_attribute%'

    auth.github:
        class: 'Hal\UI\Security\UserAuthentication\GitHubAuth'
        arguments:
            - '@doctrine.em'
            - '@auth.github.http_client'
            - '@auth.github.oauth_callback_factory'
            - '%github_auth.required_scopes%'

    auth.github_enterprise:
        class: 'Hal\UI\Security\UserAuthentication\GitHubEnterpriseAuth'
        arguments:
            - '@doctrine.em'
            - '@auth.github.http_client'
            - '@auth.github.oauth_callback_factory'
            - '%github_auth.required_scopes%'

    auth.github.http_client:
        class: 'GuzzleHttp\Client'

    auth.github.oauth_callback_factory:
        class: 'Hal\UI\Security\UserAuthentication\OAuthCallbackFactory'
        arguments:
            - '@request'
            - '@uri'
            - '%github_auth.callback_route_name%'

    ####################################################################################################################
    # authorizations
    ####################################################################################################################

    service.authorization:
        class: 'Hal\UI\Security\AuthorizationService'
        arguments:
            - '@doctrine.em'
            - '@json'
        calls:
            - ['setCache', ['@cache']]
            - ['setCacheTTL', ['%cache.permissions.ttl%']]

    service.authorization_hydrator:
        class: 'Hal\UI\Security\AuthorizationHydrator'
        arguments: ['@doctrine.em']

    service.oauth_provider.factory:
        class: 'Hal\UI\Security\OAuthProviderFactory'

    ####################################################################################################################
    # forms
    ####################################################################################################################

    csrf:
        class: 'Hal\UI\Security\CSRFManager'
        arguments: ['@clock']

    user_session.handler:
        class: 'Hal\UI\Security\UserSessionHandler'
        arguments:
            - '@doctrine.em'
            - '@service.authorization'
            - '@clock'

    ####################################################################################################################
    # crypto
    ####################################################################################################################

    encryption:
        class: 'Hal\Core\Crypto\Encryption'
        factory: ['@encryption.factory', 'getCrypto']

    encryption.factory:
        class: 'Hal\Core\Crypto\CryptoFilesystemFactory'
        arguments: ['%encrypter.secret.path%']
