services:
    ####################################################################################################################
    # vcs
    ####################################################################################################################

    vcs:
        class: 'Hal\UI\VersionControl\VCS'
        arguments:
            -
                ghe: '@vcs.github_enterprise'
                gh: '@vcs.github'

    vcs.buildable:
        class: 'Hal\UI\VersionControl\BuildableRefs'
        arguments: ['@vcs']

    vcs.github:
        class: 'Hal\UI\VersionControl\VCS\GitHubVCS'
        arguments:
            - '@github.http_cache.plugin'
            - '@github.http.builder'
            - 'https://github.com'
        calls:
            - ['setCache', ['@vcs.cache']]

    vcs.github_enterprise:
        class: 'Hal\UI\VersionControl\VCS\GitHubEnterpriseVCS'
        arguments:
            - '@github.http_cache.plugin'
            - '@github_enterprise.http.builder'
        calls:
            - ['setCache', ['@vcs.cache']]

    # vcs.git:
    #     class: 'Hal\UI\VersionControl\VCS\GitClone'
    #     arguments: []

    vcs.cache:
        parent: 'cache.memory'

    ####################################################################################################################
    # github sdk
    ####################################################################################################################

    github.http.builder:
        class: 'Github\HttpClient\Builder'
    github_enterprise.http.builder:
        class: 'Github\HttpClient\Builder'

    github.http_cache.plugin:
        class: 'Hal\Core\VersionControl\GitHub\MCPCachePlugin'
        arguments:
            - '@cache.github'
            - '@github.http_cache.http_stream_factory'
            -
                respect_cache_headers: false
                default_ttl: '%cache.github.default.ttl%'
            - '%cache.github.short.ttl%'

    github.http_cache.http_stream_factory:
        class: 'Http\Message\StreamFactory\GuzzleStreamFactory'
