parameters:
    application.title: 'HAL 9000 DEV'

    debug: true
    twig.debug: true

    doctrine.connection:
        driver:         pdo_mysql
        host:           localhost
        user:           root
        password:
        dbname:         hal

    github.token: ''
    github.app.id: ''
    github.app.secret: ''

    logger.mcp.host: 'http://qlsonictest:2581/web/core/logentries'

    redis.server: 'test.example.com:6379'
    redis.prefix: 'hal9000dev'

    encryption.secret: 'ae9c0012b8892afc69140790103f9c7241d0cfe7e4a0c8f9ae9db077a83ccc510c5b3c17dc26efd4192d9e5c6c5a1fc8'

    aws.region: ''
    aws.credentials.key: ''
    aws.credentials.secret: ''

    cli.user: ''

    encrypter.publickey: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCuK++qGa9d7ErrsqqR4JdAlJ28
        KVzQWERYbqcDWRMp1EI3bZES0KLpkub2nGDlCa1HC7/4oZzDzJkeWnkq0ChSwBuw
        4yNSLgEIySGrLd9sbIOcYEeDKrQRhXShejF4qWrr4cXrfTEm7/lI/Vo4QRC5SWCg
        fViScOUIuz9FnbkWLQIDAQAB
        -----END PUBLIC KEY-----

services:
    cache.doctrine:
        class: 'Doctrine\Common\Cache\ArrayCache'
