parameters:
    application.title: 'HAL 9000 DEV'

    debug: true
    twig.debug: true

    doctrine.connection:
        driver:         pdo_mysql
        host:           localhost
        user:           root
        password:
        dbname:         hal

    github.token: ''
    github.baseurl: 'http://git/api/v3/'

    logger.mcp.host: 'http://qlsonictest:2581/web/core/logentries'

    redis.server: 'test.example.com:6379'
    redis.prefix: 'hal9000dev'

    encryption.secret: 'ae9c0012b8892afc69140790103f9c7241d0cfe7e4a0c8f9ae9db077a83ccc510c5b3c17dc26efd4192d9e5c6c5a1fc8'
