parameters:



    doctrine.connection:
        driver:         pdo_mysql
        host:           prod.example.com
        user:           placeholder
        password:       placeholder
        dbname:         hal9000

    github.token: ''
    github.baseurl: 'http://git/api/v3/'

    logger.mcp.host: 'http://qlsonicprod:2581/web/core/logentries'

    redis.server: 'prod.example.com:6379'
    redis.prefix: 'hal9000'
