parameters:





    doctrine.connection:
        driver:         pdo_mysql
        host:           prod.example.com
        user:           placeholder
        password:       placeholder
        dbname:         hal9000

    github.token: ''
    github.app.id: ''
    github.app.secret: ''

    logger.mcp.host: 'http://qlsonicprod:2581/web/core/logentries'

    redis.server: 'prod.example.com:6379'
    redis.prefix: 'hal9000'

    encryption.secret: '26885952e5a4c316aedd6f3e7c429ed8ec2b15f55e575337b9fc75e0b78ffec1fbf81f7b7f16edf24effbac378a97cc0'

    aws.region: ''
    aws.credentials.key: ''
    aws.credentials.secret: ''

    cli.user: 'hal9000'
