system: docker:php7.1
build:
    - 'do_not_deploy_this'
    - 'bin/install --deploy --backend'
    - 'bin/deploy --deploy --backend'
    - 'docker:node5.3 bin/install --deploy --frontend'
    - 'docker:node5.3 bin/deploy --deploy --frontend'

exclude:
    - 'config/kraken.encrypter.secret'
    - 'config/hal.encrypter.secret'
