system: docker:php7.1
build:
    - 'bin/install --deploy --backend'
    - 'bin/deploy --deploy --backend'
    - 'docker:node5.3 bin/install --deploy --frontend'
    - 'docker:node5.3 bin/deploy --deploy --frontend'

exclude:
    - 'configuration/kraken.encrypter.secret'
    - 'configuration/hal.encrypter.secret'
