slim:
  debug:        true
  mode:         "development"
db.dsn:         "mysql:unix_socket=/tmp/mysql.sock;dbname=hal;charset=utf8"
db.user:        "root"
db.pass:        ""
build.user:     "mnagi"
rsync.user:     "mnagi"
github.token:   ""
github.baseurl: "http://git/api/v3/"
