version: '3'

services:

  web:
    build:
      context: ./docker
      dockerfile: ./ui.Dockerfile
      args:
        - hal_version=master
    ports:
      - 80:8000
    links:
      - postgres:postgres
      - redis:redis
    depends_on:
      - postgres
      - redis
    environment:
      DB_DRIVER: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: hal
      DB_PASSWORD: hal
      DB_DATABASE: hal
      # APP_URL: http://hal.localhost
      # APP_SECRET: 64-char hex
      # REDIS_HOST: redis

  postgres:
    image: postgres:9.6.2-alpine
    volumes:
      - /var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: hal
      POSTGRES_PASSWORD: hal
      POSTGRES_DB: hal

  redis:
    image: redis:4.0.10-alpine
    volumes:
      - /data
    restart: always
