"GET  /":                   ["loginPage"]
"POST /":                   ["loginHandler"]
"GET  /logout":             ["logoutPage"]
"GET  /a":                  ["loginGuard", "arrangementListPage"]
"GET  /a/:name":            ["loginGuard", "arrangementPage"]
"GET  /r/:name":            ["loginGuard", "repositoryPage"]
"GET  /r/:name/sync":       ["loginGuard", "syncPage"]
"POST /r/:name/sync":       ["loginGuard", "syncHandler"]
"GET  /u/:id":              ["loginGuard", "userPage"]
"GET  /admin":              ["loginGuard", "adminDashboardPage"]
"GET  /admin/arrangements": ["loginGuard", "adminArrangementsPage"]
"POST /admin/arrangements": ["loginGuard", "adminArrangementsHandler"]
"GET  /admin/repositories": ["loginGuard", "adminRepositoriesPage"]
"POST /admin/repositories": ["loginGuard", "adminRepositoriesHandler"]
"GET  /admin/envs":         ["loginGuard", "adminEnvironmentsPage"]
"POST /admin/envs":         ["loginGuard", "adminEnvironmentsHandler"]
"GET  /admin/servers":      ["loginGuard", "adminServersPage"]
"POST /admin/servers":      ["loginGuard", "adminServersHandler"]
"GET  /admin/deployments":  ["loginGuard", "adminDeploymentsPage"]
"POST /admin/deployments":  ["loginGuard", "adminDeploymentsHandler"]
"GET  /admin/users":        ["loginGuard", "adminUsersPage"]
