services:

    ######################################################################################################################
    # VALIDATORS
    ######################################################################################################################

    validator.organization:
        class: 'Hal\UI\Validator\OrganizationValidator'
        arguments: ['@doctrine.em']

    validator.environment:
        class: 'Hal\UI\Validator\EnvironmentValidator'
        arguments: ['@doctrine.em']

    validator.application:
        class: 'Hal\UI\Validator\ApplicationValidator'
        arguments: ['@doctrine.em', '@vcs']

    validator.credential:
        class: 'Hal\UI\Validator\CredentialValidator'
        arguments: ['@doctrine.em', '@encryption']

    validator.encrypted_property:
        class: 'Hal\UI\Validator\EncryptedPropertyValidator'
        arguments: ['@doctrine.em', '@encryption']

    validator.permissions:
        class: 'Hal\UI\Validator\PermissionsValidator'
        arguments: ['@doctrine.em']

    build.start.validator:
        class: 'Hal\UI\Validator\BuildValidator'
        arguments:
            - '@doctrine.em'
            - '@vcs'
            - '@service.authorization'
    release.start.validator:
        class: 'Hal\UI\Validator\ReleaseValidator'
        arguments:
            - '@doctrine.em'
            - '@service.authorization'

    group.validator:
        class: 'Hal\UI\Validator\GroupValidator'
        arguments: ['@doctrine.em']

    target.validator:
        class: 'Hal\UI\Validator\TargetValidator'
        arguments: ['@doctrine.em']

    ######################################################################################################################
    # TWIG TEMPLATING
    ######################################################################################################################

    twig.extension.hal:
        class: 'Hal\UI\Twig\HalExtension'
        arguments:
            - '@utility.time.formatter'
            - '%gravatar.fallback%'

    twig.extension.github:
        class: 'Hal\UI\Twig\GitHubExtension'
        arguments: ['@vcs']
        calls:
            - ['setCache', ['@twig.extension.github.cache']]

    twig.extension.security:
        class: 'Hal\UI\Twig\SecurityExtension'
        arguments: ['@csrf']

    twig.extension.github.cache:
        parent: 'cache.memory'

    # Twig Environment
    twig.environment:
        parent: 'panthor.twig.environment'
        calls:
            - ['addExtension', ['@twig.extension.hal']]
            - ['addExtension', ['@twig.extension.github']]
            - ['addExtension', ['@twig.extension.security']]
            - ['addGlobal', ['application_title', '%application.title%']]
            - ['addGlobal', ['application_environment', '%application.environment%']]
            - ['addGlobal', ['application_sha', '%application.sha%']]
            - ['addGlobal', ['application_version', '%application.version%']]
            - ['addGlobal', ['hal_administrators_email', '%administrator_email%']]
