parameters:
    twig.globals:
        application_title: '%application.title%'
        application_environment: '%application.environment%'
        application_sha: '%application.sha%'
        application_version: '%application.version%'
        hal_administrators_email: '%administrator_email%'

services:

    ######################################################################################################################
    # VALIDATORS
    ######################################################################################################################

    validator.organization:
        class: 'Hal\UI\Validator\OrganizationValidator'
        arguments: ['@doctrine.em']

    validator.environment:
        class: 'Hal\UI\Validator\EnvironmentValidator'
        arguments: ['@doctrine.em']

    validator.application:
        class: 'Hal\UI\Validator\ApplicationValidator'
        arguments: ['@doctrine.em', '@github']

    validator.credential:
        class: 'Hal\UI\Validator\CredentialValidator'
        arguments: ['@doctrine.em', '@encryption']

    validator.encrypted_property:
        class: 'Hal\UI\Validator\EncryptedPropertyValidator'
        arguments: ['@doctrine.em', '@encryption']

    #

    build.start.validator:
        class: 'Hal\UI\Validator\BuildValidator'
        arguments:
            - '@doctrine.em'
            - '@github'
            - '@permissions'
    push.start.validator:
        class: 'Hal\UI\Validator\PushValidator'
        arguments:
            - '@doctrine.em'
            - '@permissions'

    server.validator:
        class: 'Hal\UI\Validator\ServerValidator'
        arguments: ['@doctrine.em']

    target.validator:
        class: 'Hal\UI\Validator\TargetValidator'
        arguments: ['@doctrine.em']

    ######################################################################################################################
    # TWIG TEMPLATING
    ######################################################################################################################

    twig.extension.hal:
        class: 'Hal\UI\Twig\HalExtension'
        arguments:
            - '@utility.time.formatter'
            - '%gravatar.fallback%'

    twig.extension.hal.global:
        class: 'Hal\UI\Twig\GlobalExtension'
        arguments: ['%twig.globals%']

    twig.extension.github:
        class: 'Hal\UI\Twig\GitHubExtension'
        arguments: ['@github', '@github.url_builder']
        calls:
            - ['setCache', ['@twig.extension.github.cache']]

    twig.extension.github.cache:
        class: 'QL\MCP\Cache\MemoryCache'

    twig.extension.status:
        class: 'Hal\UI\Twig\StatusExtension'

    # Twig Environment
    twig.environment:
        parent: 'panthor.twig.environment'
        calls:
            - ['addExtension', ['@twig.extension.hal']]
            - ['addExtension', ['@twig.extension.hal.global' ]]
            - ['addExtension', ['@twig.extension.github']]
            - ['addExtension', ['@twig.extension.status']]
