services:

    api_internal.settings.favorite_applications.add:
        class: 'Hal\UI\Controllers\User\FavoriteApplications\AddFavoriteApplicationHandler'
        arguments:
            - '@doctrine.em'
            - '@uri'
            - '@json'
    api_internal.settings.favorite_applications.remove:
        class: 'Hal\UI\Controllers\User\FavoriteApplications\RemoveFavoriteApplicationHandler'
        arguments:
            - '@doctrine.em'
            - '@uri'
            - '@json'
