services:

    api_internal.settings.favorite_applications.add:
        public: true
        class: 'Hal\UI\Controllers\User\FavoriteApplications\AddFavoriteApplicationHandler'
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@uri'
            - '@json'
    api_internal.settings.favorite_applications.remove:
        public: true
        class: 'Hal\UI\Controllers\User\FavoriteApplications\RemoveFavoriteApplicationHandler'
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@uri'
            - '@json'
