parameters:

    routes.api_internal:

        api_internal:
            route: '/api/internal'
            stack: ['middleware.signed_in']

            routes:

                # Note: this endpoint is also available for direct form posts
                api_internal.favorite_applications:
                    route: '/settings/favorite-applications/{application:%r.digit%}'
                    stack: ['middleware.api_require_entity']

                    routes:
                        api_internal.settings.favorite_applications.add:
                            method: 'PUT'
                            route: ''
                            stack: ['api_internal.settings.favorite_applications.add']
                        api_internal.settings.favorite_applications.remove:
                            method: 'DELETE'
                            route: ''
                            stack: ['api_internal.settings.favorite_applications.remove']
