parameters:

    routes.api_internal:

        api_internal:
            route: '/api/internal'
            stack: ['m.iapi.signed_in']

            routes:

                # Note: this endpoint is also available for direct form posts
                api_internal.favorite_applications:
                    route: '/settings/favorite-applications/{application:%r.guid%}'
                    stack: ['m.iapi.require_entity']

                    routes:
                        settings.fav_apps.add.iapi:
                            method: 'PUT'
                            route: ''
                            stack: ['settings.fav_apps.add.iapi']
                        settings.fav_apps.remove.iapi:
                            method: 'DELETE'
                            route: ''
                            stack: ['settings.fav_apps.remove.iapi']
