services:

    build.start.api:
        public: true
        class: 'Hal\UI\Controllers\API\Build\StartBuildController'
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Hal\UI\Validator\BuildValidator'
            - '@Hal\UI\Validator\ReleaseValidator'
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\BuildNormalizer'
            - '@QL\Panthor\HTTPProblem\ProblemRendererInterface'

    deploy.api:
        public: true
        class: 'Hal\UI\Controllers\API\Release\DeployController'
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Hal\UI\Validator\ReleaseValidator'
            - '@Hal\UI\API\ResponseFormatter'
            - '@QL\Panthor\HTTPProblem\ProblemRendererInterface'
