services:

    build.start.api:
        class: 'Hal\UI\Controllers\API\Build\StartBuildController'
        arguments:
            - '@doctrine.em'
            - '@validator.build'
            - '@validator.release'
            - '@api.response_formatter'
            - '@api_normalizer.build'
            - '@problem.renderer'

    deploy.api:
        class: 'Hal\UI\Controllers\API\Release\DeployController'
        arguments:
            - '@doctrine.em'
            - '@validator.release'
            - '@api.response_formatter'
            - '@problem.renderer'
