services:

    build.start.api:
        public: true
        class: 'Hal\UI\Controllers\API\Build\StartBuildController'
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Hal\UI\Validator\BuildValidator'
            - '@Hal\UI\Validator\ReleaseValidator'
            - '@api.response_formatter'
            - '@api_normalizer.build'
            - '@problem.renderer'

    deploy.api:
        public: true
        class: 'Hal\UI\Controllers\API\Release\DeployController'
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Hal\UI\Validator\ReleaseValidator'
            - '@api.response_formatter'
            - '@problem.renderer'
