services:
    middleware.api_writes_token:
        public: true
        class: 'Hal\UI\Middleware\ACL\TokenMiddleware'
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Hal\UI\Security\UserSessionHandler'
            - '@problem.renderer'
        calls:
            - ['setLoggerMessageFactory', ['@mcp_logger_factory']]

    middleware.api_writes_require_entity:
        public: true
        class: 'Hal\UI\Middleware\RequireEntityMiddleware'
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@notFoundHandler'

    middleware.api_writes_rate_limiter:
        public: true
        class: 'Hal\UI\Middleware\APIRateLimitingMiddleware'
        arguments:
            - '@problem.renderer'
            - '@rate_limiter'
