parameters:

    routes.api_writes:

        api_writes:
            route: '/api'
            stack: ['m.api_rw.cors', 'm.api.require_auth', 'm.api_rw.rate_limiter']
            routes:
                api.build.start:
                    method: ['OPTIONS', 'POST']
                    route: '/applications/{application:%r.guid%}/build'
                    stack: ['m.api_rw.require_entity', 'build.start.api']
                api.deploy:
                    method: ['OPTIONS', 'POST']
                    route: '/builds/{build:%r.guid%}/deploy'
                    stack: ['m.api_rw.require_entity', 'deploy.api']
