parameters:
    routes.application:

        ################################################################################################################
        # REPOSITORY ROUTES
        ################################################################################################################

        applications:
            method: 'GET'
            route: '/applications'
            stack: ['middleware.login', 'applications.page']

        application:
            method: 'GET'
            route: '/applications/:application'
            stack: ['middleware.login', 'middleware.requireEntity', 'application.page']
            conditions: {application: %routes.regex.digit%}

        application.status:
            method: 'GET'
            route: '/applications/:application/status'
            stack: ['middleware.login', 'application.status.sticky.handler', 'middleware.requireEntity', 'application.status.page']
            conditions: {application: %routes.regex.digit%}

        application.add:
            method: ['GET', 'POST']
            route: '/applications/add'
            stack: ['middleware.login', 'application.add.page']

        application.edit:
            method: ['GET', 'POST']
            route: '/applications/:application/edit'
            stack: ['middleware.lead', 'middleware.requireEntity', 'application.edit.page']
            conditions: {application: %routes.regex.digit%}

        ################################################################################################################
        # REPOSITORY ROUTES - ADMIN
        ################################################################################################################

        application.remove.confirm:
            method: 'GET'
            route: '/applications/:application/remove'
            stack: ['middleware.admin', 'middleware.requireEntity', 'delete.confirm.page']
            conditions: {application: %routes.regex.digit%}
        application.remove:
            method: 'POST'
            route: '/applications/:application/remove'
            stack: ['middleware.admin', 'middleware.requireEntity', 'application.remove.handler']
            conditions: {application: %routes.regex.digit%}

        ################################################################################################################
        # DEPLOYMENT ROUTES
        ################################################################################################################

        deployment:
            method: 'GET'
            route: '/applications/:application/deployments/:deployment'
            stack: ['middleware.login', 'middleware.requireEntity', 'deployment.page']
            conditions:
                application: %routes.regex.digit%
                deployment: %routes.regex.digit%

        deployments:
            method: 'GET'
            route: '/applications/:application/deployments'
            stack: ['middleware.login', 'middleware.requireEntity', 'deployments.page']
            conditions: {application: %routes.regex.digit%}

        deployments.add:
            method: ['GET', 'POST']
            route: '/applications/:application/deployments/add'
            stack: ['middleware.lead', 'middleware.requireEntity', 'deployments.add.handler', 'deployments.add.page']
            conditions: {application: %routes.regex.digit%}

        deployment.edit:
            method: ['GET', 'POST']
            route: '/applications/:application/deployments/:deployment/edit'
            stack: ['middleware.lead', 'middleware.requireEntity', 'deployment.edit.handler', 'deployment.edit.page']
            conditions:
                application: %routes.regex.digit%
                deployment: %routes.regex.digit%

        deployment.remove.confirm:
            method: 'GET'
            route: '/applications/:application/deployments/:deployment/remove'
            stack: ['middleware.lead', 'middleware.requireEntity', 'delete.confirm.page']
            conditions:
                application: %routes.regex.digit%
                deployment: %routes.regex.digit%

        deployment.remove:
            method: 'POST'
            route: '/applications/:application/deployments/:deployment/remove'
            stack: ['middleware.lead', 'middleware.requireEntity', 'deployments.remove.handler']
            conditions:
                application: %routes.regex.digit%
                deployment: %routes.regex.digit%

        ################################################################################################################
        # REPOSITORY POOLS ROUTES
        ################################################################################################################

        pools:
            route: '/applications/:application/environments/:environment/pools'
            stack: ['middleware.login', 'middleware.requireEntity', 'pools.page']
            conditions:
                application: %routes.regex.digit%
                environment: %routes.regex.digit%

        ################################################################################################################
        # REPOSITORY ENCRYPTED PROPERTIES ROUTES
        ################################################################################################################

        encrypted:
            method: 'GET'
            route: '/applications/:application/encrypted-properties'
            stack: ['middleware.login', 'middleware.requireEntity', 'encrypted.page']
            conditions: {application: %routes.regex.digit%}

        encrypted.add:
            method: ['GET', 'POST']
            route: '/applications/:application/encrypted-properties/add'
            stack: ['middleware.lead', 'middleware.requireEntity', 'encrypted.add.handler', 'encrypted.add.page']
            conditions: {application: %routes.regex.digit%}

        encrypted.remove.confirm:
            method: 'GET'
            route: '/applications/:application/encrypted-properties/:encrypted/remove'
            stack: ['middleware.lead', 'middleware.requireEntity', 'delete.confirm.page']
            conditions:
                application: %routes.regex.digit%
                encrypted: %routes.regex.guid%
        encrypted.remove:
            method: ['POST']
            route: '/applications/:application/encrypted-properties/:encrypted/remove'
            stack: ['middleware.lead', 'middleware.requireEntity', 'encrypted.remove.handler']
            conditions:
                application: %routes.regex.digit%
                encrypted: %routes.regex.guid%
