parameters:
    routes:
        login:
            method: ['GET', 'POST']
            route: '/login'
            stack: ['login.handler', 'login.page']

        dashboard:
            method: 'GET'
            route: '/'
            stack: ['middleware.login', 'dashboard.page']

        logout:
            method: 'GET'
            route: '/logout'
            stack: ['logout.handler']

        debug:
            method: 'GET'
            route:  '/debug'
            stack:  ['middleware.super', 'debug.page']

        # github.authorization:
        #     method: 'GET'
        #     route:  '/github-authorization'
        #     stack:  ['middleware.login', 'github.authorization.page']

        # github.authorization.remove:
        #     method: ['GET', 'POST']
        #     route:  '/settings/remove-github-authorization'
        #     stack:  ['middleware.login', 'github.authorization.remove.page']

        styleguide:
            route:  '/styleguide'
            stack:  ['styleguide.page']

        styleguide.icons:
            route:  '/styleguide/icons'
            stack:  ['styleguide.icons.page']

        latest.release:
            method: 'GET'
            route:  '/latest-release'
            stack:  ['latest.release.page']
