parameters:
    routes:

        dashboard:
            method: 'GET'
            route: '/'
            stack: ['middleware.signed_in', 'dashboard.page']

        # github.authorization:
        #     method: 'GET'
        #     route:  '/github-authorization'
        #     stack:  ['middleware.login', 'github.authorization.page']

        # github.authorization.remove:
        #     method: ['GET', 'POST']
        #     route:  '/settings/remove-github-authorization'
        #     stack:  ['middleware.login', 'github.authorization.remove.page']

        ####################################################################################################################
        # SIGN-IN CONTROLLERS
        ####################################################################################################################

        signin:
            method: ['GET', 'POST']
            route: '/signin'
            stack: ['signin.middleware', 'signin.page']
        signout:
            method: 'GET'
            route: '/signout'
            stack: ['signout.page']

        ################################################################################################################
        # HELP ROUTES
        ################################################################################################################

        latest.release:
            method: 'GET'
            route:  '/latest-release'
            stack:  ['latest_release.page']

        styleguide:
            route:  '/styleguide'
            stack:  ['styleguide.page']

        styleguide.icons:
            route:  '/styleguide/icons'
            stack:  ['styleguide.icons.page']

        help:
            method: 'GET'
            route: '/help'
            stack: ['help.page']

        help.deployment:
            method: 'GET'
            route: '/help/deployment-scripting'
            stack: ['help.deployment.page']

        help.setup:
            method: 'GET'
            route: '/help/application-setup'
            stack: ['help.application_setup.page']

        ################################################################################################################
        # ORGANIZATION ROUTES
        ################################################################################################################

        organization.add:
            method: ['GET', 'POST']
            route: '/organizations/add'
            stack: ['middleware.signed_in', 'organization.add.page']

        organization.management:
            route: '/organizations/{organization:%r.digit%}'
            stack: ['middleware.signed_in', 'middleware.require_entity']
            routes:
                organization:
                    method: 'GET'
                    route: ''
                    stack: ['organization.page']
                organization.edit:
                    method: ['GET', 'POST']
                    route: '/edit'
                    stack: ['middleware.is_admin', 'organization.edit.page']
                organization.remove:
                    method: ['GET', 'POST']
                    route: '/remove'
                    stack: ['middleware.is_admin', 'middleware.removal_confirmation', 'organization.remove.handler']

        ################################################################################################################
        # APPLICATION ROUTES
        ################################################################################################################

        applications:
            method: 'GET'
            route: '/applications'
            stack: ['middleware.signed_in', 'applications.page']

        application.add:
            method: ['GET', 'POST']
            route: '/applications/add'
            stack: ['middleware.signed_in', 'application.add.page']

        application.management:
            route: '/applications/{application:%r.digit%}'
            stack: ['middleware.signed_in', 'middleware.require_entity']
            routes:
                application:
                    method: 'GET'
                    route: ''
                    stack: ['application.page']
                application.dashboard:
                    method: 'GET'
                    route: '/dashboard'
                    stack: ['application.dashboard.sticky_env.middleware', 'application.dashboard.page']
                application.sticky_pool:
                    method: 'POST'
                    route: '/environments/{environment:%r.digit%}'
                    stack: ['application.sticky_pool.handler']

                application.edit:
                    method: ['GET', 'POST']
                    route: '/edit'
                    stack: ['middleware.is_owner', 'application.edit.page']
                application.remove:
                    method: ['GET', 'POST']
                    route: '/remove'
                    stack: ['middleware.is_owner', 'middleware.removal_confirmation', 'application.remove.handler']

                # are these application routes or build/push routes?
                # It's nice to be able to use route groups to nest common url prefixes.

                build.history.page1:
                    method: 'GET'
                    route: '/builds'
                    stack: ['builds.page']
                build.history:
                    method: 'GET'
                    route: '/builds/{page:%r.digit%}'
                    stack: ['builds.page']

                push.history.page1:
                    method: 'GET'
                    route: '/pushes'
                    stack: ['pushes.page']
                push.history:
                    method: 'GET'
                    route: '/pushes/page/{page:%r.digit%}'
                    stack: ['pushes.page']

                targets:
                    method: 'GET'
                    route: '/targets'
                    stack: ['targets.page']
                target.add:
                    method: ['GET', 'POST']
                    route: '/targets/add'
                    stack: ['middleware.is_owner', 'target.add.middleware', 'target.add.page']

                target.management:
                    route: '/targets/{target:%r.digit%}'
                    stack: ['middleware.nested_entity']
                    routes:
                        target:
                            method: 'GET'
                            route: ''
                            stack: ['target.page']
                        target.edit:
                            method: ['GET', 'POST']
                            route: '/edit'
                            stack: ['middleware.is_owner', 'target.edit.middleware', 'target.edit.page']
                        target.remove:
                            method: ['GET', 'POST']
                            route: '/remove'
                            stack: ['middleware.is_owner', 'middleware.removal_confirmation', 'target.remove.handler']

                        rollback.page1:
                            method: 'GET'
                            route: '/pushes'
                            stack: ['push.rollback.page']
                        rollback:
                            method: 'GET'
                            route: '/pushes/page/{page:%r.digit%}'
                            stack: ['push.rollback.page']

                encrypted.configuration:
                    method: 'GET'
                    route: '/encrypted-configuration'
                    stack: ['encrypted.configuration.page']
                encrypted.add:
                    method: ['GET', 'POST']
                    route: '/encrypted-configuration/add'
                    stack: ['middleware.is_owner', 'encrypted.add.middleware', 'encrypted.add.page']

                encrypted.management:
                    route: '/encrypted-configuration/{encrypted:%r.guid%}'
                    stack: ['middleware.is_owner']
                    routes:
                        encrypted:
                            method: 'GET'
                            route: ''
                            stack: ['encrypted.page']
                        encrypted.remove:
                            method: ['GET', 'POST']
                            route: '/remove'
                            stack: ['middleware.removal_confirmation', 'encrypted.remove.handler']

        ################################################################################################################
        # Server Routes
        ################################################################################################################

        servers:
            method: 'GET'
            route: '/servers'
            stack: ['middleware.signed_in', 'servers.page']

        server.add:
            method: ['GET', 'POST']
            route: '/servers/add'
            stack: ['middleware.is_admin', 'server.add.page']

        server.management:
            route: '/servers/{server:%r.digit%}'
            stack: ['middleware.signed_in', 'middleware.require_entity']
            routes:
                server:
                    method: 'GET'
                    route: ''
                    stack: ['server.page']
                server.edit:
                    method: ['GET', 'POST']
                    route: '/edit'
                    stack: ['middleware.is_admin', 'server.edit.page']
                server.remove:
                    method: ['GET', 'POST']
                    route: '/remove'
                    stack: ['middleware.is_admin', 'middleware.removal_confirmation', 'server.remove.handler']

        ################################################################################################################
        # ENVIRONMENT ROUTES
        ################################################################################################################

        environments:
            method: 'GET'
            route: '/environments'
            stack: ['middleware.signed_in', 'environments.page']

        environment.add:
            method: ['GET', 'POST']
            route: '/environments/add'
            stack: ['middleware.is_admin', 'environment.add.page']

        environment.management:
            route: '/environments/{environment:%r.digit%}'
            stack: ['middleware.signed_in', 'middleware.require_entity']
            routes:
                environment:
                    method: 'GET'
                    route: ''
                    stack: ['environment.page']
                environment.edit:
                    method: ['GET', 'POST']
                    route: '/edit'
                    stack: ['middleware.is_admin', 'environment.edit.page']
                environment.remove:
                    method: ['GET', 'POST']
                    route: '/remove'
                    stack: ['middleware.is_admin', 'middleware.removal_confirmation', 'environment.remove.handler']

        ################################################################################################################
        # QUEUE ROUTES
        ################################################################################################################

        queue:
            method: 'GET'
            route: '/queue'
            stack: ['middleware.signed_in', 'queue.page']

        queue.history.page1:
            method: 'GET'
            route: '/queue-history'
            stack: ['middleware.signed_in', 'queue.history.page']

        queue.history:
            method: 'GET'
            route: '/queue-history/date/{date:%r.date%}'
            stack: ['middleware.signed_in', 'queue.history.page']

        ################################################################################################################
        # BUILD ROUTES
        ################################################################################################################

        build:
            method: 'GET'
            route: '/builds/{build:%r.build%}'
            stack: ['middleware.signed_in', 'middleware.require_entity', 'build.page']

        build.start:
            method: ['GET', 'POST']
            route: '/applications/{application:%r.digit%}/build'
            stack: ['middleware.signed_in', 'middleware.require_entity', 'build.start.middleware', 'build.start.page']

        ################################################################################################################
        # PUSH ROUTES
        ################################################################################################################

        push:
            method: 'GET'
            route: '/pushes/{push:%r.release%}'
            stack: ['middleware.signed_in', 'middleware.require_entity', 'push.page']

        push.start:
            method: ['GET', 'POST']
            route: '/builds/{build:%r.build%}/push'
            stack: ['middleware.signed_in', 'middleware.require_entity', 'push.start.middleware', 'push.start.page']

        ################################################################################################################
        # ADMIN ROUTES
        ################################################################################################################

        admin.management:
            route: '/admin'
            stack: ['middleware.is_admin']
            routes:
                admin:
                    method: 'GET'
                    route: ''
                    stack: ['admin.dashboard.page']

                admin.audit_history.page1:
                    method: 'GET'
                    route: '/audit-history'
                    stack: ['admin.audit_history.page']
                admin.audit_history:
                    method: 'GET'
                    route: '/audit-history/page/{page:%r.digit%}'
                    stack: ['admin.audit_history.page']

                ################################################################################################################
                # CREDENTIAL ROUTES
                ################################################################################################################

                admin.credentials:
                    method: 'GET'
                    route: '/credentials'
                    stack: ['admin.credentials.page']

                admin.credential.add:
                    method: ['GET', 'POST']
                    route: '/credentials/add'
                    stack: ['middleware.is_super', 'admin.credential.add.page']

                credential.management:
                    route: '/credentials/{credential:%r.guid%}'
                    stack: ['middleware.require_entity']
                    routes:
                        admin.credential:
                            method: 'GET'
                            route: ''
                            stack: ['admin.credential.page']

                        admin.credential.remove:
                            method: ['GET', 'POST']
                            route: '/remove'
                            stack: ['middleware.is_super', 'middleware.removal_confirmation', 'admin.credential.remove.handler']

        ################################################################################################################
        # SUPER ROUTES
        ################################################################################################################

        super.management:
            route: '/super'
            stack: ['middleware.is_super']
            routes:

                super.system:
                    method: 'GET'
                    route: '/system'
                    stack: ['super.system.page']
                super.system.agent:
                    method: 'GET'
                    route: '/system/{agent:%r.alphanum%}'
                    stack: ['super.system.page']

                super.caches:
                    method: ['GET', 'POST']
                    route: '/caches'
                    stack: ['super.caches.page']

                super.message:
                    method: ['GET', 'POST']
                    route: '/message'
                    stack: ['super.message.page']

        ################################################################################################################

        # routes not created yet

        settings: {route: '/derp4', stack: []}
        user: {route: '/derp11', stack: []}
        users: {route: '/derp111', stack: []}

        settings.favorite_applications.remove.handler: {route: '/derp36', stack: []}
        settings.favorite_applications.add.handler: {route: '/derp37', stack: []}
        pools: {route: '/derp38', stack: []}
        latest_release: {route: '/derp39', stack: []}

        admin.permissions: {route: '/derp55', stack: []}
        admin.credentials: {route: '/derp555', stack: []}

        api.environments: {route: '/derp14', stack: []}
        api.environment: {route: '/derp24', stack: []}

        api.application: {route: '/derp23', stack: []}
        api.applications: {route: '/derp16', stack: []}
        api.groups: {route: '/derp17', stack: []}
        api.deployment.history: {route: '/derp22', stack: []}
        api.deployment.lastpush: {route: '/derp2222', stack: []}

        api.users: {route: '/derp18', stack: []}
        api.user: {route: '/derp21', stack: []}
