parameters:
    routes:

        dashboard:
            method: 'GET'
            route: '/'
            stack: ['middleware.signed_in', 'dashboard.page']

        # github.authorization:
        #     method: 'GET'
        #     route:  '/github-authorization'
        #     stack:  ['middleware.login', 'github.authorization.page']

        # github.authorization.remove:
        #     method: ['GET', 'POST']
        #     route:  '/settings/remove-github-authorization'
        #     stack:  ['middleware.login', 'github.authorization.remove.page']

        ####################################################################################################################
        # SIGN-IN CONTROLLERS
        ####################################################################################################################

        signin:
            method: ['GET', 'POST']
            route: '/signin'
            stack: ['signin.middleware', 'signin.page']
        signout:
            method: 'GET'
            route: '/signout'
            stack: ['signout.page']

        ################################################################################################################
        # HELP ROUTES
        ################################################################################################################

        latest.release:
            method: 'GET'
            route:  '/latest-release'
            stack:  ['latest_release.page']

        styleguide:
            route:  '/styleguide'
            stack:  ['styleguide.page']

        styleguide.icons:
            route:  '/styleguide/icons'
            stack:  ['styleguide.icons.page']

        help:
            method: 'GET'
            route: '/help'
            stack: ['help.page']

        help.deployment:
            method: 'GET'
            route: '/help/deployment-scripting'
            stack: ['help.deployment.page']

        help.setup:
            method: 'GET'
            route: '/help/application-setup'
            stack: ['help.application_setup.page']

        ################################################################################################################
        # Server Routes
        ################################################################################################################

        servers:
            method: 'GET'
            route: '/servers'
            stack: ['middleware.signed_in', 'servers.page']

        server:
            method: 'GET'
            route: '/servers/{server:%r.digit%}'
            stack: ['middleware.signed_in', 'middleware.require_entity', 'server.page']

        server.management:
            route: '/servers'
            stack: ['middleware.is_admin']
            routes:
                server.add:
                    method: ['GET', 'POST']
                    route: '/servers/add'
                    stack: ['server.add.page']
                server.edit:
                    method: ['GET', 'POST']
                    route: '/{server:%r.digit%}/edit'
                    stack: ['middleware.require_entity', 'server.edit.page']
                server.remove.confirm:
                    method: 'GET'
                    route: '/{server:%r.digit%}/remove'
                    stack: ['middleware.require_entity', 'delete.confirm.page']
                server.remove:
                    method: 'POST'
                    route: '/{server:%r.digit%}/remove'
                    stack: ['middleware.require_entity', 'server.remove.page']

        ################################################################################################################
        # QUEUE ROUTES
        ################################################################################################################

        queue:
            method: 'GET'
            route: '/queue'
            stack: ['middleware.signed_in', 'queue.page']

        queue.history.page1:
            method: 'GET'
            route: '/queue-history'
            stack: ['middleware.signed_in', 'queue.history.page']

        queue.history:
            method: 'GET'
            route: '/queue-history/date/{date:%r.date%}'
            stack: ['middleware.signed_in', 'queue.history.page']

        ################################################################################################################
        # BUILD ROUTES
        ################################################################################################################

        build:
            method: 'GET'
            route: '/builds/{build:%r.build%}'
            stack: ['middleware.signed_in', 'middleware.require_entity', 'build.page']

        build.start:
            method: ['GET', 'POST']
            route: '/applications/{application:%r.digit%}/build'
            stack: ['middleware.signed_in', 'middleware.require_entity', 'build.start.handler', 'build.start.page']

        ################################################################################################################
        # PUSH ROUTES
        ################################################################################################################

        push:
            method: 'GET'
            route: '/pushes/{push:%r.release%}'
            stack: ['middleware.signed_in', 'middleware.require_entity', 'push.page']

        push.start:
            method: ['GET', 'POST']
            route: '/builds/{build:%r.build%}/push'
            stack: ['middleware.signed_in', 'middleware.require_entity', 'push.start.handler', 'push.start.page']

        ################################################################################################################

        # routes not created yet

        admin: {route: '/derp1', stack: []}
        applications: {route: '/derp3', stack: []}
        settings: {route: '/derp4', stack: []}
        application.status: {route: '/derp7', stack: []}
        user: {route: '/derp11', stack: []}
        environment: {route: '/derp12', stack: []}

        application: {route: '/derp34', stack: []}
        deployment: {route: '/derp33', stack: []}

        api.environments: {route: '/derp14', stack: []}
        api.applications: {route: '/derp16', stack: []}
        api.groups: {route: '/derp17', stack: []}
        api.users: {route: '/derp18', stack: []}

        api.user: {route: '/derp21', stack: []}
        api.deployment: {route: '/derp22', stack: []}
        api.application: {route: '/derp23', stack: []}
        api.environment: {route: '/derp24', stack: []}
        api.event: {route: '/derp25', stack: []}
