# Application specific endpoints and controllers go here
services:

  ######################################################################################################################
  # ENVIRONMENT CONTROLLERS
  ######################################################################################################################

  environments.page:
    class: 'QL\Hal\Controllers\Environment\EnvironmentsController'
    arguments:
      - @environments.twig
      - @layout
      - @environment.repo
  environments.twig:
    parent: 'twig.template'
    arguments: ['environment/environments.twig']

  environment.page:
    class: 'QL\Hal\Controllers\Environment\EnvironmentController'
    arguments:
      - @environment.twig
      - @layout
      - @environment.repo
      - @server.repo
  environment.twig:
    parent: 'twig.template'
    arguments: ['environment/environment.twig']

  environment.admin.reorder.page:
    class: 'QL\Hal\Controllers\Environment\AdminReorderController'
    arguments:
      - @environment.admin.reorder.twig
      - @layout
      - @environment.repo
  environment.admin.reorder.twig:
    parent: 'twig.template'
    arguments: ['environment/admin.reorder.twig']
  environment.admin.reorder.handle:
    class: 'QL\Hal\Controllers\Environment\AdminReorderHandle'
    arguments:
      - @environment.repo
      - @doctrine.em
      - @session
      - @url.helper

  environment.admin.add.page:
    class: 'QL\Hal\Controllers\Environment\AdminAddController'
    arguments:
      - @environment.admin.add.twig
      - @layout
      - @environment.repo
      - @doctrine.em
      - @session
      - @url.helper
  environment.admin.add.twig:
    parent: 'twig.template'
    arguments: ['environment/admin.add.twig']
  environment.admin.add.handle:
    parent: environment.admin.add.page

  environment.admin.edit.page:
    class: 'QL\Hal\Controllers\Environment\AdminEditController'
    arguments:
      - @environment.admin.edit.twig
      - @layout
      - @environment.repo
      - @doctrine.em
      - @session
      - @url.helper
  environment.admin.edit.twig:
    parent: 'twig.template'
    arguments: ['environment/admin.edit.twig']
  environment.admin.edit.handle:
    parent: environment.admin.edit.page

  environment.admin.remove.handle:
    class: 'QL\Hal\Controllers\Environment\AdminRemoveHandle'
    arguments:
      - @environment.repo
      - @server.repo
      - @doctrine.em
      - @session
      - @url.helper

  ######################################################################################################################
  # USER CONTROLLERS
  ######################################################################################################################

  user.page:
    class: 'QL\Hal\Controllers\User\UserController'
    arguments:
      - @user.twig
      - @layout
      - @pushPermissionService
      - @ldapService
      - @user.repo
      - @user
      - @doctrine.em
  user.twig:
    parent: 'twig.template'
    arguments:
      - 'user/user.twig'

  users.page:
    class: 'QL\Hal\Controllers\User\UsersController'
    arguments:
      - @users.twig
      - @layout
      - @user.repo
  users.twig:
    parent: 'twig.template'
    arguments:
      - 'user/users.twig'

  user.edit.page:
    class: 'QL\Hal\Controllers\User\EditController'
    arguments:
      - @user.edit.twig
      - @layout
      - @pushPermissionService
      - @ldapService
      - @user.repo
      - @doctrine.em
      - @url.helper
      - @user
  user.edit.twig:
    parent: 'twig.template'
    arguments:
      - 'user/user.edit.twig'
  user.edit.handle:
    class: 'QL\Hal\Controllers\User\EditHandle'
    arguments:
      - @user.repo
      - @url.helper

  ######################################################################################################################
  # GENERAL USE CONTROLLERS
  ######################################################################################################################

  static.controller:
    class: 'QL\Hal\Controllers\StaticController'

  denied.page:
    parent: 'static.controller'
    arguments: ['@denied.twig', 403]
  denied.twig:
    parent: 'twig.template'
    arguments: ['denied.html.twig']

  ######################################################################################################################
  # UTILITIES
  ######################################################################################################################

  twig.template:
    class: 'Twig_Template'
    factory_service: 'twigEnv'
    factory_method: 'loadTemplate'
