imports:
  - resource: di.yml
  - resource: ../vendor/ql/hal-core/config/di.yml

parameters:
  debug:            true

  # OLD DB (need both for now)
  db.dsn:           "mysql:host=localhost;dbname=hal;charset=utf8"
  db.user:          "root"
  db.pass:          ""

  # NEW DB (need both for now)
  doctrine.mappings:
    - "%root%/src/QL/Hal/Core/Entity"
  doctrine.devmode:   true
  doctrine.connection:
    driver:         pdo_mysql
    host:           localhost
    user:           root
    password:
    dbname:         hal

  build.user:       "mcolf"
  build.dir:        "/tmp"
  build.async:      false
  rsync.user:       "mcolf"
  github.token:     ""
  github.baseurl:   "http://git/api/v3/"
  ldap.host:        "ldap.example.com"
  ldap.domain:      "MI"
  ldap.baseDn:      "DC=mi,DC=corp"
  ldap.username:    "placeholder"
  ldap.password:    "placeholder"

  email.hostname:     mail.example.com
  email.subject:      "HAL9000 - {repo} [{status}][{env}][{server}]"
  email.notify:       "matthewcolf@quickenloans.com"
  email.notify.error: false
  build.log.level:    100
  build.log.name:     hal9000
  build.date.format:  ""

  mcpLogger.applicationId: '200947'
  mcpLogger.host: 'qlsonictest'

  # These help with development

  # godmode - set this to your common id and you will be an admin
  debug.godmode: 0
