imports:
  - resource: ../vendor/ql/hal-core/config/di.yml
  - resource: di.yml
  - resource: routes.yml

parameters:
  debug: true

  doctrine.devmode: true
  doctrine.connection:
    driver:         pdo_mysql
    host:           localhost
    user:           root
    password:
    dbname:         hal

  github.token: ''
  github.baseurl: 'http://git/api/v3/'

  ldap.host: 'ldap.example.com'
  ldap.domain: 'MI'
  ldap.baseDn: 'DC=mi,DC=corp'
  ldap.username: 'placeholder'
  ldap.password: 'placeholder'

  logger.mcp.host: 'http://qlsonictest:2581/web/core/logentries'

  # These help with development

  # godmode - set this to your common id and you will be an admin
  debug.godmode: 0
