parameters:
    # use this file for default settings that can be overridden by dev|test|prod config
    application.title: 'HAL 9000'

    debug: false
    twig.debug: false
    debug.godmode: 0

    slim.configuration:
        debug: '%debug%'

    ldap.host: 'ldap.example.com'
    ldap.domain: 'MI'
    ldap.baseDn: 'DC=mi,DC=corp'
    ldap.username: ''
    ldap.password: ''

    doctrine.devmode: false

    navigation.list:
        dashboard: 'Dashboard'
        queue: 'Queue'
        groups: 'Groups'
        repositories: 'Repositories'
        servers: 'Servers'
        environments: 'Environments'
        users: 'Users'
        logs: 'Logs'
        admin: 'Admin'
        help: 'Help'

    # To set a specific cache time for a route, add the route name as a key,
    # and the time to cache in seconds. If not specified, default time is 10 seconds.
    api.cachetimes:
        # these are lower because having the most update to date status is critical
        api.build: 5
        api.push: 5
        api.queue: 0 # the queue api uses no caching
        api.queue.refresh: 0 # the queue api uses no caching

    cache.permissions.ttl: 600
    cache.doctrine.ttl: 600

    # base58
    unique.alphabet: '123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ'

    # Cookie settings
    session.cookie.configuration:
        lifetime: '1 day'
    cookie.preferences.ttl: '5 years'
