slim:
  debug:        true
  mode:         "development"
db.dsn:         "mysql:host=test.example.com;dbname=hal9000_test;charset=utf8"
db.user:        "placeholder"
db.pass:        "placeholder"
build.user:     "bschiefer"
rsync.user:     "bschiefer"
github.token:   ""
github.baseurl: "http://git/api/v3/"
ldap.host:      "ldap.example.com"
ldap.domain:    "MI"
ldap.baseDn:    "DC=mi,DC=corp"

# These help with development

# godmode - set this to your common id and you will be an admin
debug.godmode: 0
