parameters:
    app.title: 'HAL 9000 DEV'


    doctrine.connection:
        driver:         pdo_mysql
        host:           localhost
        user:           root
        password:
        dbname:         hal

    github.token: ''
    github.baseurl: 'http://git/api/v3/'

    logger.mcp.host: 'http://qlsonictest:2581/web/core/logentries'

    doctrine.devmode: true
