imports:
    - resource: ../vendor/ql/hal-core/config/di.yml
    - resource: di.yml
    - resource: config.global.yml
    - resource: config.env.yml
    - resource: routes.yml

parameters:
    # environment independent parameters
    application.id: '200947'
    application.major.version: '2'

    # Replaced before di compiling
    application.sha: ''

    slim.hooks:
        slim.before:
            - 'slim.hook.logger'
            - 'slim.hook.errors'
        slim.before.router:
            - 'slim.hook.routes'
