"login":
  "method":     "GET"
  "route":      "/"
  "stack":      ["loginPage"]

"login_handle":
  "method":     "POST"
  "route":      "/"
  "stack":      ["loginHandler"]

"logout":
  "method":     "GET"
  "route":      "/logout"
  "stack":      ["loginBouncer", "logoutPage"]

"arrangements":
  "method":     "GET"
  "route":      "/a"
  "stack":      ["loginBouncer", "arrangementListPage"]

"arrangement":
  "method":     "GET"
  "route":      "/a/:name"
  "stack":      ["loginBouncer", "arrangementPage"]
  "conditions":
    "name":     "[A-Za-z0-9_-]+"

"repository":
  "method":     "GET"
  "route":      "/r/:name(/page/:page)"
  "stack":      ["loginBouncer", "repositoryPage"]
  "conditions":
    "name":     "[A-Za-z0-9_-]+"
    "page":     "[0-9]+"

"repository_sync":
  "method":     "GET"
  "route":      "/r/:name/sync"
  "stack":      ["loginBouncer", "syncPage"]
  "conditions":
    "name":     "[A-Za-z0-9_-]+"

"repository_sync_handler":
  "method":     "POST"
  "route":      "/r/:name/sync"
  "stack":      ["loginBouncer", "syncHandler"]
  "conditions":
    "name":     "[A-Za-z0-9_-]+"

"user":
  "method":     "GET"
  "route":      "/u/:id"
  "stack":      ["loginBouncer", "userPage"]
  "conditions":
    "id":       "[\d]+"

"admin":
  "method":     "GET"
  "route":      "/admin"
  "stack":      ["loginBouncer", "adminBouncer", "adminDashboardPage"]

"admin_arrangements":
  "method":     "GET"
  "route":      "/admin/arrangements"
  "stack":      ["loginBouncer", "adminBouncer", "adminArrangementsPage"]

"admin_arrangements_handle":
  "method":     "POST"
  "route":      "/admin/arrangements"
  "stack":      ["loginBouncer", "adminBouncer", "adminArrangementsHandler"]

"admin_repositories":
  "method":     "GET"
  "route":      "/admin/repositories"
  "stack":      ["loginBouncer", "adminBouncer", "adminRepositoriesPage"]

"admin_repositories_handler":
  "method":     "POST"
  "route":      "/admin/repositories"
  "stack":      ["loginBouncer", "adminBouncer", "adminRepositoriesHandler"]

"admin_repositories_remove":
  "method":     "GET"
  "route":      "/admin/repositories/:id/remove"
  "stack":      ["loginBouncer", "adminBouncer", "adminRepositoriesRemoveHandler"]
  "conditions":
    "id":       "[\d]+"

"admin_environments":
  "method":     "GET"
  "route":      "/admin/envs"
  "stack":      ["loginBouncer", "adminBouncer", "adminEnvironmentsPage"]

"admin_environments_handler":
  "method":     "POST"
  "route":      "/admin/envs"
  "stack":      ["loginBouncer", "adminBouncer", "adminEnvironmentsHandler"]

"admin_servers":
  "method":     "GET"
  "route":      "/admin/servers"
  "stack":      ["loginBouncer", "adminBouncer", "adminServersPage"]

"admin_servers_handler":
  "method":     "POST"
  "route":      "/admin/servers"
  "stack":      ["loginBouncer", "adminBouncer", "adminServersHandler"]

"admin_deployments":
  "method":     "GET"
  "route":      "/admin/deployments"
  "stack":      ["loginBouncer", "adminBouncer", "adminDeploymentsPage"]

"admin_deployments_handler":
  "method":     "POST"
  "route":      "/admin/deployments"
  "stack":      ["loginBouncer", "adminBouncer", "adminDeploymentsHandler"]

"admin_deployments_remove":
  "method":     "GET"
  "route":      "/admin/deployments/:id/remove"
  "stack":      ["loginBouncer", "adminBouncer", "adminDeploymentsRemoveHandler"]
  "conditions":
    "id":       "[\d]+"

"admin_users":
  "method":     "GET"
  "route":      "/admin/users"
  "stack":      ["loginBouncer", "adminBouncer", "adminUsersPage"]

"admin_permissions":
  "method":     "GET"
  "route":      "/admin/permissions"
  "stack":      ["loginBouncer", "adminBouncer", "adminPermissionsPage"]

"admin_github_users":
  "method":     "GET"
  "route":      "/admin/github-users"
  "stack":      ["loginBouncer", "adminBouncer", "adminGithubUsersApi"]
"admin_github_repos":
  "method":     "GET"
  "route":      "/admin/github-repos/:username"
  "stack":      ["loginBouncer", "adminBouncer", "adminGithubReposApi"]
"admin_github_pulls":
  "method":     "GET"
  "route":      "/github/pulls/:username/:repository"
  "stack":      ["loginBouncer", "githubPullsApi"]
