login:
  method:     "GET"
  route:      "/"
  stack:
    - login.page

login.handle:
  method:     "POST"
  route:      "/"
  stack:
    - login.handle

logout:
  method:     "GET"
  route:      "/logout"
  stack:
    - login.bouncer
    - logout.handle

profile:
  method:     "GET"
  route:      "/profile(/:id)"
  stack:
    - login.bouncer
    - profile.page
  conditions:
    id:       "[\d]+"

groups:
  method:     "GET"
  route:      "/groups"
  stack:
    - login.bouncer
    - groups.page

group:
  method:     "GET"
  route:      "/group/:group"
  stack:
    - login.bouncer
    - group.page
  conditions:
    name:     "[A-Za-z0-9_-]+"

repo:
  method:     "GET"
  route:      "/repository/:repo"
  stack:
    - login.bouncer
    - repository.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"

########################################################################################################################
# BUILD ROUTES
########################################################################################################################

build.history:
  method:     "GET"
  route:      "/repository/:repo/build/history(/page/:page)"
  stack:
    - login.bouncer
    - repository.build.history.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"
    page:     "[0-9]+"

build:
  method:     "GET"
  route:      "/build/:build"
  stack:
    - login.bouncer
    - build.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"
    build:    "[A-Za-z0-9_-]+"

build.start:
  method:     "GET"
  route:      "/repository/:repo/build"
  stack:
    - login.bouncer
    - repository.build.start.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"

### STUB - FIX ME
build.handle:
  method:     "POST"
  route:      "/repository/:repo/build"
  stack:
    - login.bouncer
    - nyi.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"

########################################################################################################################
# PUSH ROUTES
########################################################################################################################

push.history:
  method:     "GET"
  route:      "/repository/:repo/push/history(/page/:page)"
  stack:
    - login.bouncer
    - repository.push.history.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"
    page:     "[0-9]+"

rollback:
  method:     "GET"
  route:      "/repository/:repo/rollback/:server"
  stack:
    - login.bouncer
    - rollback.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"
    server:   "[0-9]+"

push.start:
  method:     "GET"
  route:      "/repository/:repo/build/:build/push"
  stack:
    - login.bouncer
    - build.push.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"
    build:    "[A-Za-z0-9_-]+"

### STUB - FIX ME
# Push Handle
push.handle:
  method:     "POST"
  route:      "/repository/:repo/build/:build/push"
  stack:
    - login.bouncer
    - nyi.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"
    build:    "[A-Za-z0-9_-]+"

push:
  method:     "GET"
  route:      "/push/:push"
  stack:
    - login.bouncer
    - push.page
  conditions:
    push:     "[0-9]+"

########################################################################################################################
# SERVER ROUTES
########################################################################################################################

servers:
  method:     "GET"
  route:      "/servers"
  stack:
    - login.bouncer
    - servers.page

server:
  method:     "GET"
  route:      "/server/:server"
  stack:
    - login.bouncer
    - server.page
  conditions:
    server:   "[A-Za-z0-9_-]+"

########################################################################################################################
# ADMIN REPO ROUTES
########################################################################################################################

### STUB - FIX ME
admin.repos:
  method:     "GET"
  route:      "/admin/repositories"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page

### STUB - FIX ME
admin.repo.create:
  method:     "GET"
  route:      "/admin/repository/create"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page

### STUB - FIX ME
admin.repo.create.handle:
  method:     "POST"
  route:      "/admin/repository/create"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page

### STUB - FIX ME
admin.repo:
  method:     "GET"
  route:      "/admin/repository/:repo"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    repo:     "[A-Za-z0-0_-]+"

### STUB - FIX ME
admin.repo.edit.handle:
  method:     "POST"
  route:      "/admin/repository/:repo/edit"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"

### STUB - FIX ME
admin.repo.delete.handle:
  method:     "GET"
  route:      "/admin/repository/:repo/delete"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"

### STUB - FIX ME
admin.repo.deployment.create:
  method:     "GET"
  route:      "/admin/repository/:repo/deployment/create"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"

### STUB - FIX ME
admin.repo.deployment.create.handle:
  method:     "POST"
  route:      "/admin/repository/:repo/deployment/create"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"

### STUB - FIX ME
admin.repo.deployment:
  method:     "GET"
  route:      "/admin/repository/:repo/deployment/:deploy"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"
    deploy:   "[0-9]+"

### STUB - FIX ME
admin.repo.deployment.handle:
  method:     "POST"
  route:      "/admin/repository/:repo/deployment/:deploy"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    repo:     "[A-Za-z0-9_-]+"
    deploy:   "[0-9]+"

########################################################################################################################
# ADMIN GROUP ROUTES
########################################################################################################################

### STUB - FIX ME
admin.groups:
  method:     "GET"
  route:      "/admin/groups"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page

### STUB - FIX ME
admin.group.create:
  method:     "GET"
  route:      "/admin/group/create"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page

### STUB - FIX ME
admin.group.create.handle:
  method:     "POST"
  route:      "/admin/group/create"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page

### STUB - FIX ME
admin.group:
  method:     "GET"
  route:      "/admin/group/:group/edit"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    group:   "[A-Za-z0-9_-]+"

### STUB - FIX ME
admin.group.edit.handle:
  method:     "POST"
  route:      "/admin/group/:group/edit"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    group:    "[A-Za-z0-9_-]+"

### STUB - FIX ME
admin.group.delete.handle:
  method:     "GET"
  route:      "/admin/group/:group/delete"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    group:    "[A-Za-z0-9_-]+"

########################################################################################################################
# ADMIN ENVIRONMENT ROUTES
########################################################################################################################

### STUB - FIX ME
admin.envs:
  method:     "GET"
  route:      "/admin/environments"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page

### STUB - FIX ME
admin.env.create:
  method:     "GET"
  route:      "/admin/environment/create"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page

### STUB - FIX ME
admin.env.create.handle:
  method:     "POST"
  route:      "/admin/environment/create"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page

### STUB - FIX ME
admin.env:
  method:     "GET"
  route:      "/admin/environment/:env"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    env:      "[A-Za-z0-9_-]+"

### STUB - FIX ME
admin.env.edit.handle:
  method:     "POST"
  route:      "/admin/environment/:env/edit"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    env:      "[A-Za-z0-9_-]+"

### STUB - FIX ME
admin.env.delete.handle:
  method:     "GET"
  route:      "/admin/environment/:env/delete"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    env:      "[A-Za-z0-9_-]+"

########################################################################################################################
# ADMIN SERVER ROUTES
########################################################################################################################

### STUB - FIX ME
admin.servers:
  method:     "GET"
  route:      "/admin/servers"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page

### STUB - FIX ME
admin.server.create:
  method:     "GET"
  route:      "/admin/server/create"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page

### STUB - FIX ME
admin.server.create:
  method:     "POST"
  route:      "/admin/server/create"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page

### STUB - FIX ME
admin.server:
  method:     "GET"
  route:      "/admin/server/:server"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    server:   "[A-Za-z0-9_-]+"

### STUB - FIX ME
admin.server.edit.handle:
  method:     "POST"
  route:      "/admin/server/:server/edit"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    server:   "[A-Za-z0-9_-]+"

### STUB - FIX ME
admin.server.delete.handle:
  method:     "GET"
  route:      "/admin/server/:server/delete"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page
  conditions:
    server:   "[A-Za-z0-9_-]+"

########################################################################################################################
# ADMIN USER ROUTES
########################################################################################################################

### STUB - FIX ME
admin.users:
  method:     "GET"
  route:      "/admin/users"
  stack:
    - login.bouncer
    - admin.bouncer
    - nyi.page

########################################################################################################################
# API ROUTES
########################################################################################################################

