QL\Kraken\Entity\Configuration:
    type: entity
    table: kraken_configuration

    id:
        id:
            column: id
            type: string
            length: 40

    fields:

        configuration:
            column: configuration
            type: string
        checksum:
            column: checksum
            type: string
            length: 500
        created:
            column: created_time
            type: timepoint
            nullable: true

    manyToOne:

        environment:
            targetEntity: Environment
            joinColumn:
                name: environment_id
                referencedColumnName: id

        application:
            targetEntity: Application
            joinColumn:
                name: application_id
                referencedColumnName: id
