QL\Kraken\Entity\Configuration:
    type: entity
    table: kraken_configuration

    id:
        id:
            column: id
            type: string
            length: 40

    manyToOne:

        environment:
            targetEntity: Environment
            joinColumn:
                name: environment_id
                referencedColumnName: id

        application:
            targetEntity: Application
            joinColumn:
                name: application_id
                referencedColumnName: id
