parameters:
    routes.kraken.regex.digit: '[0-9]+'
    routes.kraken.regex.hex: '[0-9a-fA-F]{32}'

    kraken.routes:

        ################################################################################################################
        # CORE ROUTES
        ################################################################################################################

        kraken:
            route: '/kraken'
            stack: ['login.bouncer', 'kraken.page']

        kraken.applications:
            route: '/kraken/applications'
            stack: ['login.bouncer', 'kraken.applications.page']

        kraken.environments:
            route: '/kraken/environments'
            stack: ['login.bouncer', 'kraken.environments.page']

        ################################################################################################################
        # APPLICATION
        ################################################################################################################

        kraken.application:
            route: '/kraken/application/:application'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.application.page']
            conditions: {application: %routes.kraken.regex.hex%}
        kraken.status:
            route: '/kraken/application/:application/status'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.status.page']
            conditions: {application: %routes.kraken.regex.hex%}

        ################################################################################################################
        # CONFIGURATION
        ################################################################################################################

        kraken.configuration:
            route: '/kraken/application/:application/configuration/:configuration'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.application.configuration.deployed.page']
            conditions:
                application: %routes.kraken.regex.hex%
                configuration: %routes.kraken.regex.hex%

        kraken.configuration.compare:
            route: '/kraken/application/:application/configuration/:configuration/compare'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.configuration.compare.page']
            conditions:
                application: %routes.kraken.regex.hex%
                configuration: %routes.kraken.regex.hex%

        kraken.configuration.history.page1:
            route: '/kraken/application/:application/configurations'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.configuration.history.page']
            conditions:
                application: %routes.kraken.regex.hex%
        kraken.configuration.history:
            route: '/kraken/application/:application/configuration/page/:page'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.configuration.history.page']
            conditions:
                application: %routes.kraken.regex.hex%
                page: %routes.kraken.regex.digit%

        kraken.configuration.latest:
            route: '/kraken/application/:application/environment/:environment'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.configuration.latest.page']
            conditions:
                application: %routes.kraken.regex.hex%
                environment: %routes.kraken.regex.hex%

        ################################################################################################################
        # CRUD
        ################################################################################################################

        # add application
        kraken.add_application:
            route: '/kraken/application/add'
            stack: ['login.bouncer', 'kraken.add_application.page']

        # add environment
        kraken.add_environment:
            route: '/kraken/environment/add'
            stack: ['login.bouncer', 'kraken.add_environment.page']

        ################################################################################################################
        # CRUD - APPLICATION
        ################################################################################################################

        # add environment to application
        kraken.application.add_target:
            route: '/kraken/application/:application/environments'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.application.add_target.page']
            conditions: {application: %routes.kraken.regex.hex%}

        ################################################################################################################
        # CRUD - SCHEMA
        ################################################################################################################

        kraken.schema:
            route: '/kraken/application/:application/schema'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.application.schema.page']
            conditions:
                application: %routes.kraken.regex.hex%

        kraken.schema.add:
            route: '/kraken/application/:application/schema/add'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.schema.add.page']
            conditions: {application: %routes.kraken.regex.hex%}

        kraken.schema.edit:
            route: '/kraken/schema/:schema/edit'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.schema.edit.page']
            conditions:
                schema: %routes.kraken.regex.hex%

        kraken.schema.remove.confirm:
            method: 'GET'
            route: '/kraken/:schema/remove'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.schema.remove.page']
            conditions:
                schema: %routes.kraken.regex.hex%
        kraken.schema.remove:
            method: 'POST'
            route: '/kraken/:schema/remove'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.schema.remove.handler']
            conditions:
                schema: %routes.kraken.regex.hex%

        ################################################################################################################
        # CRUD - PROPERTY
        ################################################################################################################

        kraken.property.add:
            route: '/kraken/application/:application/environment/:environment/add'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.property.add.page']
            conditions:
                application: %routes.kraken.regex.hex%
                environment: %routes.kraken.regex.hex%

        kraken.property:
            route: '/kraken/property/:property'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.property.page']
            conditions:
                property: %routes.kraken.regex.hex%

        kraken.property.edit:
            route: '/kraken/property/:property/edit'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.property.edit.page']
            conditions:
                property: %routes.kraken.regex.hex%

        ################################################################################################################
        # DEPLOY
        ################################################################################################################

        # deploy configuration to target
        kraken.deploy:
            method: ['GET']
            route: '/kraken/targets/:target/deploy'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.deploy.page']
            conditions: {target: %routes.kraken.regex.hex%}
        kraken.deploy.handler:
            method: ['POST']
            route: '/kraken/targets/:target/deploy'
            stack: ['login.bouncer', 'kraken.middleware.require.entity', 'kraken.deploy.handler']
            conditions: {target: %routes.kraken.regex.hex%}
