imports:
    - resource: '../vendor/ql/mcp-logger/config/config.php'
    - resource: '../vendor/hal/hal-core/config/config.php'
    - resource: '../vendor/ql/mcp-panthor/configuration/*.yml'
    - resource: 'services/*.php'

    - resource: 'services.php'
    - resource: 'parameters.yaml'

    - resource: 'ui/*.yaml'
    - resource: 'ui/*.php'
    - resource: 'api/*.yaml'
    - resource: 'api/*.php'
    - resource: 'api-internal/*.yaml'
    - resource: 'api-writes/*.yaml'
    - resource: 'api-writes/*.php'
