parameters:
    ############################################################################
    # application
    ############################################################################
    application.id: 'halui'
    application.title: 'Hal'
    application.environment: '%env(string:ENVIRONMENT)%'

    application.version: '%env(string:HAL_VERSION)%'
    application.sha: '%env(string:HAL_APPLICATION_SHA)%'

    hal.pushfile.path: '%root%/.hal9000.push.yml'

    ############################################################################
    # general
    ############################################################################
    root: '%env(string:HAL_ROOT)%'
    base_url: '%env(string:HAL_BASEURL)%'
    administrator_email: '%env(string:HAL_ADMIN_EMAIL)%'

    # Route condition regexes
    r.alphanum: '[A-Za-z0-9]+'
    r.digit: '[0-9]+'
    r.guid: '[0-9a-zA-Z\-]{32,36}'
    r.date: '[0-9]{4}-[0-9]{2}-[0-9]{2}'
    r.api.queue: '[A-Za-z0-9\+\-\.]+'

    gravatar.fallback: 'hal.computer/img/hal-profile-200.jpg'

    ############################################################################
    # panthor
    ############################################################################
    # debug: '%env(bool:HAL_DEBUG_ON)%'
    # slim.settings.display_errors: '%env(bool:HAL_DEBUG_ON)%'

    # routes.cached: 'config/routes.cached.php'
    # routes.cache_disabled: '%env(bool:HAL_ROUTES_DISABLE_CACHE_ON)%'
    global_middleware:
        - 'Hal\UI\Middleware\LoggerGlobalMiddleware'
        - 'Hal\UI\Middleware\TemplateContextGlobalMiddleware'
        - 'QL\Panthor\Middleware\EncryptedCookiesMiddleware'
        - 'Hal\UI\Middleware\FlashGlobalMiddleware'
        - 'QL\Panthor\Middleware\SessionMiddleware'
        - 'Hal\UI\Middleware\UserSessionGlobalMiddleware'
        - 'Hal\UI\Middleware\SrsBusinessGlobalMiddleware'
        - 'Hal\UI\Middleware\SystemSettingsGlobalMiddleware'

    error_handling.html_template: 'error.twig'

    ############################################################################
    # logging
    ############################################################################
    error_handling.log_stacktrace: '%env(HAL_LOG_STACKTRACES_ON)%'
    mcp_logger.default_properties:
        applicationID: '%application.id%'
        serverEnvironment: '%application.environment%'

    ############################################################################
    # doctrine
    ############################################################################
    doctrine.cache.delimiter: '%cache.delimiter%'

    ############################################################################
    # twig
    ############################################################################
    # twig.debug: '%env(bool:HAL_DEBUG_TWIG_ON)%'

    ############################################################################
    # auth
    ############################################################################
    ldap.host: '%env(HAL_LDAP_HOST)%'
    ldap.port: '%env(HAL_LDAP_PORT)%'
    ldap.domain: '%env(HAL_LDAP_DOMAIN)%'
    ldap.base_dn: '%env(HAL_LDAP_BASE_DN)%'

    github_auth.required_scopes: ['read:user', 'read:org', 'user:email']
    github_auth.callback_route_name: 'signin.oauth2_callback'

    ############################################################################
    # cache
    ############################################################################
    redis.server: '%env(HAL_REDIS_SERVER)%'
    redis.prefix: '%env(HAL_REDIS_PREFIX)%'

    cache.type.api: '%env(HAL_CACHE_API)%'
    cache.type.main: '%env(HAL_CACHE_MAIN)%'
    cache.type.github: '%env(HAL_CACHE_GITHUB)%'

    cache.permissions.ttl: 1800
    cache.server.ttl: 300
    cache.stats.ttl: 900
    cache.page.ttl: 300
    cache.github.default_ttl: 60

    cache.delimiter: '.'

    ############################################################################
    # api configuration
    ############################################################################
    # To set a specific cache time for a route, add the route name as a key and the time to cache in seconds.
    # Default time is 10 seconds.
    api.cachetimes:
        # these are lower because having the most update to date status is critical
        api.build: 5
        api.push: 5
        api.queue: 0 # the queue api uses no caching
        api.queue.refresh: 0 # the queue api uses no caching

    # Allowed requests for route x user per MINUTE
    # Default is 120 per minute (2 req/sec)
    api.ratelimits:
        api.build.start: 10
        api.deploy: 20

    api.cors.allowed_headers:
        'Content-Type': true
        'Authorization': true

    api.cors.allowed_origins:
        '*': true

    ############################################################################
    # cookie
    ############################################################################
    session.lifetime: '+5 days'
    cookie.settings.lifetime: '+5 years'
    cookie.preferences.ttl: '+1 year'
    cookie.settings:
        expires: '%cookie.settings.lifetime%'
        path: '/'
        domain: ''
        secure: '%cookie.settings.secure%'
        httpOnly: '%cookie.settings.http_only%'

    ############################################################################
    # credentials / encryption
    ############################################################################
    encryption.secret_path: '%env(HAL_CRYPTO_SECRETPATH)%'

    aws.use_host_credentials: '%env(bool:HAL_AWS_CREDENTIALS_USE_HOST)%'
    aws.host_credentials_path: '%env(HAL_AWS_HOST_CREDENTIALS_PATH)%'

    ############################################################################
    # authentication
    ############################################################################
    ldap.query_restriction:
        objectCategory: 'person'
        # objectClass: 'user'
    ldap.unique_attribute: 'sAMAccountName'
