QL\Kraken\Entity\Configuration:
    type: entity
    table: kraken_configuration

    id:
        id:
            column: id
            type: string
            length: 40

    fields:

        isSuccess:
            column: success
            type: boolean
        audit:
            column: audit
            type: text
            length: 65535
        created:
            column: created_time
            type: timepoint
            nullable: true

    manyToOne:

        environment:
            targetEntity: Environment
            joinColumn:
                name: environment_id
                referencedColumnName: id

        application:
            targetEntity: Application
            joinColumn:
                name: application_id
                referencedColumnName: id

        user:
            cache: {usage : READ_ONLY}
            targetEntity: QL\Hal\Core\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: UserId
