QL\Kraken\Entity\ConfigurationProperty:
    type: entity
    table: kraken_configuration_property

    id:
        id:
            column: id
            type: string
            length: 32
            options: {fixed: true}

    fields:

        key:
            column: property_key
            type: string
            length: 150
        dataType:
            column: data_type
            type: propertyenum
        isSecure:
            column: secure
            type: boolean
        value:
            column: value
            type: text
            length: 65535
        checksum:
            column: checksum
            type: string
            length: 40
        created:
            column: created_time
            type: timepoint
            nullable: true

    manyToOne:

        configuration:
            targetEntity: Configuration
            joinColumn:
                name: configuration_id
                referencedColumnName: id
        property:
            targetEntity: Property
            joinColumn:
                name: property_id
                referencedColumnName: id
        schema:
            targetEntity: Schema
            joinColumn:
                name: schema_id
                referencedColumnName: id
