parameters:
    application.environment: 'prod'






    database.username: 'placeholder'
    database.database: 'hal9000'
    database.server: 'prod.example.com'

    github.token: ''
    github.app.id: ''
    github.app.secret: ''

    logger.mcp.host: 'http://qlsonicprod:2581/web/core/logentries'

    redis.server: 'prod.example.com:6379'
    redis.prefix: 'hal9000'

    cookie.encryption.secret: '26885952e5a4c316aedd6f3e7c429ed8ec2b15f55e575337b9fc75e0b78ffec1fbf81f7b7f16edf24effbac378a97cc0'

    aws.region: 'us-west-2'
    aws.credentials.key: ''
    aws.credentials.secret: ''

    cli.user: 'hal9000'

    encrypter.publickey: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCj+Ln/5AWjAnM9FJi7zgv/IqRj
        8CReT3KupTRaZ+N80coa5OfsCnUSHbbyzc8YHsTSca5RHhda71ibPheYMLkE+JgW
        BtpfPvGc3OuoNVZk/gE5pcAXHGyn/I7DGWln1slYAaFY/vwpCO1lj4iMJQEv+4Va
        BlVv60PT/P0W0gLZ2wIDAQAB
        -----END PUBLIC KEY-----

    kraken.environmentalize: false

    hal.agents:
        - 'ql1halpragt1'
        - 'ql2halpragt1'
