#!/usr/bin/env php
<?php

namespace QL\Hal\Bin;

$root = __DIR__ . '/..';
if (!$container = @include $root . '/configuration/bootstrap.php') {
    echo "The application failed to start.\n";
    exit(1);
}

$redis = $container->get('redis');

// List keys in the hal namespace
$keys = $redis->keys('*');

sort($keys);
print_r($keys);


// For emergency clearing of doctrine metadata
// $keys = $redis->keys('doctrine:*');
// $delete = true;
// if ($delete) {
//     foreach ($keys as $k) {
//         $k = str_replace('hal9000:', '', $k);
//         echo sprintf("\n Delete %s", $k);
//         $redis->del($k);
//     }

//     // List keys in the hal namespace
//     $keys = $redis->keys('doctrine:*');
//     sort($keys);
//     print_r($keys);
// }


echo "\n";
