services:

    ####################################################################################################################
    # POOL CONTROLLERS
    ####################################################################################################################

    pools.page:
        class: 'Hal\UI\Controllers\Application\Pool\PoolsController'
        arguments:
            - '@pools.twig'
            - '@sticky.pool'
            - '@doctrine.em'
            - '@hal.application'
            - '@hal.environment'
    pools.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/pool/pools.twig']]]

    deployment_view.add.page:
        class: 'Hal\UI\Controllers\Application\Pool\AddViewController'
        arguments:
            - '@deployment_view.add.twig'
            - '@slim.request'
            - '@session.flasher'
            - '@pools'
            - '@doctrine.random'
            - '@doctrine.em'
            - '@hal.application'
            - '@hal.environment'
            - '@currentUser'
    deployment_view.add.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/pool/view.add.twig']]]

    deployment_view.page:
        class: 'Hal\UI\Controllers\Application\Pool\ViewController'
        arguments:
            - '@deployment_view.twig'
            - '@doctrine.em'
            - '@hal.view'
    deployment_view.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/pool/view.twig']]]

    deployment_view.edit.page:
        class: 'Hal\UI\Controllers\Application\Pool\EditViewController'
        arguments:
            - '@deployment_view.edit.twig'
            - '@slim.request'
            - '@session.flasher'
            - '@pools'
            - '@doctrine.em'
            - '@hal.view'
    deployment_view.edit.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/pool/view.edit.twig']]]

    deployment_view.remove.handler:
        class: 'Hal\UI\Controllers\Application\Pool\RemoveViewHandler'
        arguments:
            - '@doctrine.em'
            - '@session.flasher'
            - '@pools'
            - '@hal.view'

    pool.add.page:
        class: 'Hal\UI\Controllers\Application\Pool\AddPoolController'
        arguments:
            - '@pool.add.twig'
            - '@slim.request'
            - '@session.flasher'
            - '@pools'
            - '@doctrine.random'
            - '@doctrine.em'
            - '@hal.view'
    pool.add.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/pool/pool.add.twig']]]

    pool.edit.page:
        class: 'Hal\UI\Controllers\Application\Pool\EditPoolController'
        arguments:
            - '@pool.edit.twig'
            - '@slim.request'
            - '@session.flasher'
            - '@pools'
            - '@doctrine.em'
            - '@hal.view'
            - '@hal.pool'
    pool.edit.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/pool/pool.edit.twig']]]

    pool.remove.handler:
        class: 'Hal\UI\Controllers\Application\Pool\RemovePoolHandler'
        arguments:
            - '@doctrine.em'
            - '@session.flasher'
            - '@pools'
            - '@hal.view'
            - '@hal.pool'

    pool.deployment.add.handler:
        class: 'Hal\UI\Controllers\Application\Pool\Deployment\AddHandler'
        arguments:
            - '@slim.request'
            - '@slim.response'
            - '@session.flasher'
            - '@slim.halt'
            - '@json'
            - '@url'
            - '@doctrine.em'
            - '@hal.view'
            - '@hal.pool'

    pool.deployment.remove.handler:
        class: 'Hal\UI\Controllers\Application\Pool\Deployment\RemoveHandler'
        arguments:
            - '@slim.request'
            - '@slim.response'
            - '@session.flasher'
            - '@doctrine.em'
            - '@hal.pool'
            - '@hal.deployment'
