services:
    ####################################################################################################################
    # APPLICATION CONTROLLERS
    ####################################################################################################################

    applications.page:
        class: 'QL\Hal\Controllers\Application\ApplicationsController'
        arguments:
            - @applications.twig
            - @doctrine.em
    applications.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/applications.twig']]]

    application.page:
        class: 'QL\Hal\Controllers\Application\ApplicationController'
        arguments:
            - @application.twig
            - @doctrine.em
            - @hal.application
    application.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/application.twig']]]

    application.status.page:
        class: 'QL\Hal\Controllers\Application\ApplicationStatusController'
        arguments:
            - @application.status.twig
            - @doctrine.em
            - @sticky.environment
            - @hal.application
    application.status.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/status.twig']]]

    application.status.sticky.handler:
        class: 'QL\Hal\Controllers\Application\ApplicationStatusEnvironmentSaveHandler'
        arguments:
            - @doctrine.em
            - @slim.request
            - @url
            - @sticky.environment
            - @slim.route.parameters

    application.add.page:
        class: 'QL\Hal\Controllers\Application\AddApplicationController'
        arguments:
            - @application.add.twig
            - @doctrine.em
            - @github
            - @session.flasher
            - @slim.request
    application.add.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/application.add.twig']]]

    application.edit.page:
        class: 'QL\Hal\Controllers\Application\EditApplicationController'
        arguments:
            - @application.edit.twig
            - @doctrine.em
            - @hal.application
            - @session.flasher
            - @slim.request
    application.edit.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/application.edit.twig']]]

    application.remove.handler:
        class: 'QL\Hal\Controllers\Application\RemoveApplicationController'
        arguments:
            - @doctrine.em
            - @session.flasher
            - @hal.application

    ####################################################################################################################
    # DEPLOYMENT CONTROLLERS
    ####################################################################################################################

    deployment.page:
        class: 'QL\Hal\Controllers\Application\Deployment\DeploymentController'
        arguments:
            - @deployment.twig
            - @eb
            - @hal.deployment
    deployment.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/deployment/deployment.twig']]]

    deployments.page:
        class: 'QL\Hal\Controllers\Application\Deployment\DeploymentsController'
        arguments:
            - @deployments.twig
            - @doctrine.em
            - @hal.application
    deployments.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/deployment/deployments.twig']]]

    deployments.add.page:
        class: 'QL\Hal\Controllers\Application\Deployment\AddDeploymentController'
        arguments:
            - @deployments.add.twig
            - @doctrine.em
            - @url
            - @slim.request
            - @hal.application
    deployments.add.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/deployment/deployments.add.twig']]]

    deployments.add.handler:
        class: 'QL\Hal\Controllers\Application\Deployment\AddDeploymentHandler'
        arguments:
            - @slim.request
            - @deployments.add.handler.form
            - @deployments.add.handler.json
    deployments.add.handler.form:
        class: 'QL\Hal\Controllers\Application\Deployment\AddDeploymentFormHandler'
        arguments:
            - @doctrine.em
            - @deployment.validator
            - @session.flasher
            - @twig.context
            - @slim.request
            - @hal.application
    deployments.add.handler.json:
        class: 'QL\Hal\Controllers\Application\Deployment\AddDeploymentJsonHandler'
        arguments:
            - @doctrine.em
            - @deployment.validator
            - @slim.halt
            - @json
            - @url
            - @slim.request
            - @slim.response
            - @hal.application
    deployment.validator:
        class: 'QL\Hal\Validator\DeploymentValidator'
        arguments: [@doctrine.em]

    deployment.edit.page:
        class: 'QL\Hal\Controllers\Application\Deployment\EditDeploymentController'
        arguments:
            - @deployment.edit.twig
            - @slim.request
            - @hal.deployment
    deployment.edit.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/deployment/deployments.edit.twig']]]
    deployment.edit.handler:
        class: 'QL\Hal\Controllers\Application\Deployment\EditDeploymentHandler'
        arguments:
            - @doctrine.em
            - @deployment.validator
            - @session.flasher
            - @twig.context
            - @slim.request
            - @hal.deployment

    deployments.remove.handler:
        class: 'QL\Hal\Controllers\Application\Deployment\RemoveDeploymentHandler'
        arguments:
            - @doctrine.em
            - @session.flasher
            - @hal.deployment

    ####################################################################################################################
    # ENCRYPTED PROPERTIES CONTROLLERS
    ####################################################################################################################

    encrypted.page:
        class: 'QL\Hal\Controllers\Application\EncryptedProperty\EncryptedPropertiesController'
        arguments:
            - @encrypted.twig
            - @doctrine.em
            - @hal.application
    encrypted.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/encrypted/encrypted.properties.twig']]]

    encrypted.add.page:
        class: 'QL\Hal\Controllers\Application\EncryptedProperty\AddEncryptedPropertyController'
        arguments:
            - @encrypted.add.twig
            - @doctrine.em
            - @slim.request
            - @hal.application
    encrypted.add.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/encrypted/add.encrypted.property.twig']]]
    encrypted.add.handler:
        class: 'QL\Hal\Controllers\Application\EncryptedProperty\AddEncryptedPropertyHandler'
        arguments:
            - @doctrine.em
            - @encrypter
            - @session.flasher
            - @twig.context
            - @slim.request
            - @doctrine.random
            - @hal.application
    encrypted.remove.handler:
        class: 'QL\Hal\Controllers\Application\EncryptedProperty\RemoveEncryptedPropertyHandler'
        arguments:
            - @doctrine.em
            - @session.flasher
            - @slim.request
            - @hal.encrypted
