services:

    application.status.page:
        class: 'Hal\UI\Controllers\Application\ApplicationStatusController'
        arguments:
            - '@application.status.twig'
            - '@doctrine.em'
            - '@sticky.environment'
            - '@pools'
            - '@hal.application'
    application.status.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/status.twig']]]

    application.status.sticky.handler:
        class: 'Hal\UI\Controllers\Application\ApplicationStatusEnvironmentSaveHandler'
        arguments:
            - '@doctrine.em'
            - '@slim.request'
            - '@url'
            - '@sticky.environment'
            - '@slim.route.parameters'

    application.sticky.pool.handler:
        class: 'Hal\UI\Controllers\Application\StickyPoolHandler'
        arguments:
            - '@doctrine.em'
            - '@slim.request'
            - '@session.flasher'
            - '@sticky.pool'
            - '@slim.response'
            - '@json'
            - '@hal.application'
            - '@hal.environment'

    application.add.page:
        class: 'Hal\UI\Controllers\Application\AddApplicationController'
        arguments:
            - '@application.add.twig'
            - '@doctrine.em'
            - '@github'
            - '@permissions'
            - '@session.flasher'
            - '@slim.request'
            - '@currentUser'
            - '@doctrine.random'
            - '%github.site.baseurl%'
    application.add.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/application.add.twig']]]

    application.edit.page:
        class: 'Hal\UI\Controllers\Application\EditApplicationController'
        arguments:
            - '@application.edit.twig'
            - '@doctrine.em'
            - '@github'
            - '@hal.application'
            - '@session.flasher'
            - '@slim.request'
            - '%github.site.baseurl%'
    application.edit.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/application.edit.twig']]]

    application.remove.handler:
        class: 'Hal\UI\Controllers\Application\RemoveApplicationController'
        arguments:
            - '@doctrine.em'
            - '@session.flasher'
            - '@hal.application'

    ####################################################################################################################
    # DEPLOYMENT CONTROLLERS
    ####################################################################################################################

    deployment.page:
        class: 'Hal\UI\Controllers\Application\Deployment\DeploymentController'
        arguments:
            - '@deployment.twig'
            - '@hal.deployment'
    deployment.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/deployment/deployment.twig']]]

    deployments.page:
        class: 'Hal\UI\Controllers\Application\Deployment\DeploymentsController'
        arguments:
            - '@deployments.twig'
            - '@doctrine.em'
            - '@hal.application'
    deployments.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/deployment/deployments.twig']]]

    deployments.add.page:
        class: 'Hal\UI\Controllers\Application\Deployment\AddDeploymentController'
        arguments:
            - '@deployments.add.twig'
            - '@doctrine.em'
            - '@url'
            - '@slim.request'
            - '@hal.application'
    deployments.add.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/deployment/deployments.add.twig']]]

    deployments.add.handler:
        class: 'Hal\UI\Controllers\Application\Deployment\AddDeploymentHandler'
        arguments:
            - '@slim.request'
            - '@deployments.add.handler.form'
            - '@deployments.add.handler.json'
    deployments.add.handler.form:
        class: 'Hal\UI\Controllers\Application\Deployment\AddDeploymentFormHandler'
        arguments:
            - '@doctrine.em'
            - '@deployment.validator'
            - '@session.flasher'
            - '@twig.context'
            - '@slim.request'
            - '@hal.application'
    deployments.add.handler.json:
        class: 'Hal\UI\Controllers\Application\Deployment\AddDeploymentJsonHandler'
        arguments:
            - '@doctrine.em'
            - '@deployment.validator'
            - '@slim.halt'
            - '@json'
            - '@url'
            - '@slim.request'
            - '@slim.response'
            - '@hal.application'
    deployment.validator:
        class: 'Hal\UI\Validator\DeploymentValidator'
        arguments: ['@doctrine.em']

    deployment.edit.page:
        class: 'Hal\UI\Controllers\Application\Deployment\EditDeploymentController'
        arguments:
            - '@deployment.edit.twig'
            - '@slim.request'
            - '@doctrine.em'
            - '@hal.deployment'
    deployment.edit.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/deployment/deployments.edit.twig']]]
    deployment.edit.handler:
        class: 'Hal\UI\Controllers\Application\Deployment\EditDeploymentHandler'
        arguments:
            - '@doctrine.em'
            - '@deployment.validator'
            - '@session.flasher'
            - '@twig.context'
            - '@slim.request'
            - '@hal.deployment'

    deployments.remove.handler:
        class: 'Hal\UI\Controllers\Application\Deployment\RemoveDeploymentHandler'
        arguments:
            - '@doctrine.em'
            - '@session.flasher'
            - '@hal.deployment'

    ####################################################################################################################
    # POOL CONTROLLERS
    ####################################################################################################################

    pools.page:
        class: 'Hal\UI\Controllers\Application\Pool\PoolsController'
        arguments:
            - '@pools.twig'
            - '@sticky.pool'
            - '@doctrine.em'
            - '@hal.application'
            - '@hal.environment'
    pools.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/pool/pools.twig']]]

    deployment_view.add.page:
        class: 'Hal\UI\Controllers\Application\Pool\AddViewController'
        arguments:
            - '@deployment_view.add.twig'
            - '@slim.request'
            - '@session.flasher'
            - '@pools'
            - '@doctrine.random'
            - '@doctrine.em'
            - '@hal.application'
            - '@hal.environment'
            - '@currentUser'
    deployment_view.add.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/pool/view.add.twig']]]

    deployment_view.page:
        class: 'Hal\UI\Controllers\Application\Pool\ViewController'
        arguments:
            - '@deployment_view.twig'
            - '@doctrine.em'
            - '@hal.view'
    deployment_view.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/pool/view.twig']]]

    deployment_view.edit.page:
        class: 'Hal\UI\Controllers\Application\Pool\EditViewController'
        arguments:
            - '@deployment_view.edit.twig'
            - '@slim.request'
            - '@session.flasher'
            - '@pools'
            - '@doctrine.em'
            - '@hal.view'
    deployment_view.edit.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/pool/view.edit.twig']]]

    deployment_view.remove.handler:
        class: 'Hal\UI\Controllers\Application\Pool\RemoveViewHandler'
        arguments:
            - '@doctrine.em'
            - '@session.flasher'
            - '@pools'
            - '@hal.view'

    pool.add.page:
        class: 'Hal\UI\Controllers\Application\Pool\AddPoolController'
        arguments:
            - '@pool.add.twig'
            - '@slim.request'
            - '@session.flasher'
            - '@pools'
            - '@doctrine.random'
            - '@doctrine.em'
            - '@hal.view'
    pool.add.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/pool/pool.add.twig']]]

    pool.edit.page:
        class: 'Hal\UI\Controllers\Application\Pool\EditPoolController'
        arguments:
            - '@pool.edit.twig'
            - '@slim.request'
            - '@session.flasher'
            - '@pools'
            - '@doctrine.em'
            - '@hal.view'
            - '@hal.pool'
    pool.edit.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/pool/pool.edit.twig']]]

    pool.remove.handler:
        class: 'Hal\UI\Controllers\Application\Pool\RemovePoolHandler'
        arguments:
            - '@doctrine.em'
            - '@session.flasher'
            - '@pools'
            - '@hal.view'
            - '@hal.pool'

    pool.deployment.add.handler:
        class: 'Hal\UI\Controllers\Application\Pool\Deployment\AddHandler'
        arguments:
            - '@slim.request'
            - '@slim.response'
            - '@session.flasher'
            - '@slim.halt'
            - '@json'
            - '@url'
            - '@doctrine.em'
            - '@hal.view'
            - '@hal.pool'

    pool.deployment.remove.handler:
        class: 'Hal\UI\Controllers\Application\Pool\Deployment\RemoveHandler'
        arguments:
            - '@slim.request'
            - '@slim.response'
            - '@session.flasher'
            - '@doctrine.em'
            - '@hal.pool'
            - '@hal.deployment'

    ####################################################################################################################
    # ENCRYPTED PROPERTIES CONTROLLERS
    ####################################################################################################################

    encrypted.page:
        class: 'Hal\UI\Controllers\Application\EncryptedProperty\EncryptedPropertiesController'
        arguments:
            - '@encrypted.twig'
            - '@doctrine.em'
            - '@hal.application'
    encrypted.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/encrypted/encrypted.properties.twig']]]

    encrypted.add.page:
        class: 'Hal\UI\Controllers\Application\EncryptedProperty\AddEncryptedPropertyController'
        arguments:
            - '@encrypted.add.twig'
            - '@doctrine.em'
            - '@slim.request'
            - '@hal.application'
    encrypted.add.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/encrypted/add.encrypted.property.twig']]]

    encrypted.add.handler:
        class: 'Hal\UI\Controllers\Application\EncryptedProperty\AddEncryptedPropertyHandler'
        arguments:
            - '@doctrine.em'
            - '@encrypter'
            - '@session.flasher'
            - '@twig.context'
            - '@slim.request'
            - '@doctrine.random'
            - '@hal.application'

    encrypted.view.page:
        class: 'Hal\UI\Controllers\Application\EncryptedProperty\UnencryptedController'
        arguments:
            - '@encrypted.view.twig'
            - '@hal.encrypted'
            - '@decrypter'
    encrypted.view.twig:
        parent: 'twig.auto.template'
        calls: [['setTemplate', ['application/encrypted/unencrypted.twig']]]

    encrypted.remove.handler:
        class: 'Hal\UI\Controllers\Application\EncryptedProperty\RemoveEncryptedPropertyHandler'
        arguments:
            - '@doctrine.em'
            - '@session.flasher'
            - '@slim.request'
            - '@hal.encrypted'
