services:

    ####################################################################################################################
    # NON-DATABASE SERVICES
    ####################################################################################################################

    ldap.auth:
        class: 'QL\Hal\Auth'
        arguments:
            - '@ldap.auth.symfony'
            - '%ldap.base_dn%'
            - '%ldap.domain%'
            - 'person'
            - 'sAMAccountName'

    ldap.auth.symfony:
        class: 'Symfony\Component\Ldap\Ldap'
        factory: ['Symfony\Component\Ldap\Ldap', 'create']
        arguments:
            - 'ext_ldap'
            -
                host: '%ldap.host%'
                port: '%ldap.port%'

    permissions:
        class: 'QL\Hal\Service\PermissionService'
        arguments:
            - '@doctrine.em'
            - '@github'
            - '@json'
            - '%permissions.check.github%'
        calls:
            - ['setCache', ['@cache']]
            - ['setCacheTTL', ['%cache.permissions.ttl%']]

    global.message:
        class: 'QL\Hal\Service\GlobalMessageService'
        arguments: ['@redis']

    sticky.environment:
        class: 'QL\Hal\Service\StickyEnvironmentService'
        arguments:
            - '@slim.cookies'
            - '@json'
            - '%cookie.preferences.ttl%'

    sticky.pool:
        class: 'QL\Hal\Service\StickyPoolService'
        arguments:
            - '@slim.cookies'
            - '@json'
            - '%cookie.preferences.ttl%'

    stats:
        class: 'QL\Hal\Service\StatsService'
        arguments:
            - '@doctrine.em'
            - '@clock'
            - '%date.timezone%'
        calls:
            - ['setCache', ['@cache']]
            - ['setCacheTTL', ['%cache.stats.ttl%']]

    pools:
        class: 'QL\Hal\Service\PoolService'
        arguments:
            - '@doctrine.em'
            - '@sticky.pool'
        calls:
            - ['setCache', ['@cache']]
            - ['setCacheTTL', ['%cache.stats.ttl%']]

    redis:
        class: 'Predis\Client'
        arguments:
            - '%redis.server%'
            - {prefix: '%redis.prefix%:'}

    github:
        class: 'QL\Hal\Service\GitHubService'
        arguments:
            - '@github.repoService'
            - '@github.repoCommitService'
            - '@github.gitRefService'
            - '@github.gitCommitService'
            - '@github.pullService'
            - '@github.userService'
            - '@github.orgService'
            - '@github.orgMemberService'
            - '@github.pager'

    service.event_logs:
        class: 'QL\Hal\Service\EventLogService'
        arguments:
            - '@redis'
            - '@json'
            - '@clock'

    acl:
        class: 'QL\Hal\ACL'
        arguments:
            - '@denied.twig'
            - '@slim.halt'
            - '@permissions'
            - '@currentUser'

    ####################################################################################################################
    # Crypto
    ####################################################################################################################

    encrypter:
        class: 'QL\Hal\Core\Crypto\Encrypter'
        arguments: ['%encrypter.publickey%']

    decrypter:
        class: 'QL\Hal\Core\Crypto\Decrypter'
        factory: ['@decrypter.factory', 'getAsymmetricDecrypter']
        lazy: true

    decrypter.factory:
        class: 'QL\Hal\Core\Crypto\CryptoFactory'
        arguments:
            - '@encrypter.encryptedkey.squished'
            - '@encrypter.secret.file'

    encrypter.encryptedkey.squished:
        class: 'stdClass'
        factory: ['QL\Hal\Application\Stringify', 'squish']
        arguments: ['%encrypter.encryptedkey%']

    encrypter.secret.file:
        class: 'stdClass'
        factory: ['QL\Panthor\Utility\Stringify', 'template']
        arguments: ['%%s/%%s', ['@root', '%encrypter.hal.secret.path%']]

    ######################################################################################################################
    # TWIG STUFF
    ######################################################################################################################

    twig.auto.template:
        parent: 'twig.template'
        class: 'QL\Hal\Application\AutoRenderingTemplate'
        calls: [['setResponse', ['@slim.response']]]

    twig.extension.hal:
        class: 'QL\Hal\Twig\HalExtension'
        arguments:
            - '@slim.request'
            - '@slim.cookies'
            - '@session'
            - '@global.message'
            - '@utility.time.formatter'
            - '@utility.name.formatter'
            - '%gravatar.fallback%'

    twig.extension.hal.global:
        class: 'QL\Hal\Twig\GlobalExtension'
        arguments:
            - '@service_container'
            - '@session'
            -
                applicationTitle: '%application.title%'
                applicationSha: '%application.sha%'
                applicationVersion: '%application.major.version%'
                applicationEnvironment: '%application.environment%'

    twig.extension.hal.lazy:
        class: 'QL\Hal\Twig\LazyUserExtension'
        arguments: ['@service_container', '@session']

    twig.extension.permissions:
        class: 'QL\Hal\Twig\PermissionsExtension'
        arguments: ['@permissions']

    twig.extension.github:
        class: 'QL\Hal\Twig\GitHubExtension'
        arguments: ['@github', '@github.url_builder']
        calls:
            - ['setCache', ['@twig.extension.github.cache']]

    twig.extension.github.cache:
        class: 'QL\MCP\Cache\MemoryCache'

    twig.extension.status:
        class: 'QL\Hal\Twig\StatusExtension'

    # Twig Environment
    twig.environment:
        parent: 'panthor.twig.environment'
        calls:
            - ['addExtension', ['@twig.extension.hal']]
            - ['addExtension', ['@twig.extension.hal.global' ]]
            - ['addExtension', ['@twig.extension.hal.lazy' ]]
            - ['addExtension', ['@twig.extension.permissions']]
            - ['addExtension', ['@twig.extension.github']]
            - ['addExtension', ['@twig.extension.status']]

    ####################################################################################################################
    # HTTP Plug
    ####################################################################################################################
    github.http.cache.plugin:
        class: 'QL\Hal\Github\MCPCachePlugin'
        arguments:
            - '@cache'
            - '@plug.http_stream_factory'
            - {respect_cache_headers: false, default_ttl: '%cache.github.default.ttl%'}
            - '%cache.github.short.ttl%'

    plug.http_stream_factory:
        class: 'Http\Message\StreamFactory\GuzzleStreamFactory'

    ####################################################################################################################
    # GitHub
    ####################################################################################################################

    github.oauth:
        class: 'QL\Hal\Github\OAuthHandler'
        arguments:
            - '@guzzle'
            - '%github.baseurl%'
            - '%github.site.baseurl%'
            - '%github.app.id%'
            - '%github.app.secret%'

    github.url_builder:
        class: 'QL\Hal\Github\GitHubURLBuilder'
        arguments: ['@github', '%github.site.baseurl%']

    github.client:
        class: 'QL\Hal\Github\EnterpriseClient'
        arguments: ['@github.http.builder', null, '%github.site.baseurl%']
        configurator: ['@github.client.configurator', configure]
        calls:
            - ['authenticate', ['%github.token%', null, 'http_token']]

    github.client.configurator:
        class: 'QL\Hal\Github\GithubClientConfigurator'
        arguments:
            - '@github.http.cache.plugin'
            - '@github.http.builder'

    github.http.builder:
        class: 'Github\HttpClient\Builder'

    github.pager:
        class: 'Github\ResultPager'
        arguments: ['@github.client']

    github.pullService:
        class: 'Github\Api\PullRequest'
        arguments: ['@github.client']

    github.gitRefService:
        class: 'Github\Api\GitData\References'
        arguments: ['@github.client']
    github.gitCommitService:
        class: 'Github\Api\GitData\Commits'
        arguments: ['@github.client']

    github.repoService:
        class: 'Github\Api\Repo'
        arguments: ['@github.client']
    github.repoCommitService:
        class: 'Github\Api\Repository\Commits'
        arguments: ['@github.client']

    github.userService:
        class: 'Github\Api\User'
        arguments: ['@github.client']
    github.orgService:
        class: 'QL\Hal\Github\Organization'
        arguments: ['@github.client']
    github.orgMemberService:
        class: 'Github\Api\Organization\Members'
        arguments: ['@github.client']
