parameters:
    # use this file for default settings that can be overridden by dev|test|prod config
    application.title: 'HAL 9000'
    application.kraken.title: 'Kraken'
    application.environment: ''

    ############################################################################
    # Encrypted Properties - Replaced at deploy time
    ############################################################################

    ldap.password: ''
    database.password: ''

    ############################################################################
    # debug
    ############################################################################

    debug: false
    twig.debug: false

    # slim
    slim.configuration:
        debug: %debug%

    ############################################################################
    # ldap
    ############################################################################

    ldap.host: 'ldap.example.com'
    ldap.domain: 'MI'
    ldap.baseDn: 'DC=mi,DC=corp'
    ldap.username: ''

    ############################################################################
    # doctrine
    ############################################################################

    doctrine.devmode: false

    # Replaced by env
    database.username: ''
    database.server: ''
    database.database: ''

    doctrine.connection:
        driver: pdo_mysql
        host: %database.server%
        user: %database.username%
        password: %database.password%
        dbname: %database.database%

    ############################################################################
    # caching
    ############################################################################

    # To set a specific cache time for a route, add the route name as a key,
    # and the time to cache in seconds. If not specified, default time is 10 seconds.
    api.cachetimes:
        # these are lower because having the most update to date status is critical
        api.build: 5
        api.push: 5
        api.queue: 0 # the queue api uses no caching
        api.queue.refresh: 0 # the queue api uses no caching

    # 30 min for permissions
    cache.permissions.ttl: 1800
    cache.doctrine.ttl: 600
    cache.server.ttl: 300
    cache.stats.ttl: 900
    cache.page.ttl: 300

    ############################################################################
    # configuration
    ############################################################################

    github.baseurl: 'http://git/api/v3/'
    github.site.baseurl: 'http://git/'

    unique.alphabet: '123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ'
    unique.size: 4
    date.timezone: 'America/Detroit'

    ############################################################################
    # cookie
    ############################################################################

    navigation.list:
        dashboard: 'Dashboard'
        queue: 'Queue'
        applications: 'Applications'
        servers: 'Servers'
        environments: 'Environments'
        users: 'Users'
        admin: 'Admin'
        help: 'Help'
        kraken: 'Kraken'

    session.encryption.secret: ''
    session.cookie.configuration:
        lifetime: '5 days'
    cookie.preferences.ttl: '5 years'

    ############################################################################
    # permission settings
    ############################################################################

    # Check GitHub collaborators for non-prod permissions
    permissions.check.github: true

    ############################################################################
    # agent
    ############################################################################

    hal.agents: []

    ############################################################################
    # kraken
    ############################################################################

    kraken.environmentalize: true
    encrypter.kraken.secret.path: 'configuration/kraken.encrypter.secret'
