hal_core:
    proxy_dir: '.doctrine'

    database_connection:
        driver: 'pdo_mysql'
        user: 'hal'
        password: ''
        host: '127.0.0.1'
        port: ''
        dbname: 'hal'

    cache:
        type: predis
        predis_service_id: 'redis'
        lvl2_enabled: true
        lvl2_ttl: 600
        lvl2_lock: 60


    lazy_user_loader: 'doctrine.utility.lazy.user'

    clock:
        service_id: 'clock'
        date_timezone: '%date.timezone%'

    event_listeners:
        onFlush: ['doctrine.listener.logger']
        prePersist: ['doctrine.listener.persist']


mcp_logger:
       syslog_options:
            ident: 'hal-%application.id%'
            facility: 'LOG_USER'
            silent: true
            options: ['LOG_ODELAY', 'LOG_CONS']

       default_properties:
            applicationID: '%application.id%'
            serverEnvironment: '%application.environment%'

parameters:

    application.title: 'Hal'
    application.environment: 'dev'

    ############################################################################
    # panthor
    ############################################################################

    routes.cache_disabled: false

    ############################################################################
    # debug
    ############################################################################

    debug: false
    symfony.debug: false
    twig.debug: false

    ############################################################################
    # ldap
    ############################################################################

    ldap.host: 'ldap.example.com'
    ldap.domain: 'MI'
    ldap.base_dn: 'dc=mi,dc=corp'
    ldap.port: 389

    ############################################################################
    # error handling and logging
    ############################################################################

    error_handling.log_stacktrace: true

    ############################################################################
    # caching
    ############################################################################

    # To set a specific cache time for a route, add the route name as a key,
    # and the time to cache in seconds. If not specified, default time is 10 seconds.
    api.cachetimes:
        # these are lower because having the most update to date status is critical
        api.build: 5
        api.push: 5
        api.queue: 0 # the queue api uses no caching
        api.queue.refresh: 0 # the queue api uses no caching

    # 30 min for permissions
    cache.permissions.ttl: 1800
    cache.server.ttl: 300
    cache.stats.ttl: 900
    cache.page.ttl: 300
    cache.github.default.ttl: 60
    cache.github.short.ttl: 20

    ############################################################################
    # configuration
    ############################################################################

    github.baseurl: 'http://git/api/v3'
    github.site.baseurl: 'http://git'

    unique.alphabet: '123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ'
    unique.size: 4
    date.timezone: 'America/Detroit'

    gravatar.fallback: 'skluck.github.io/hal/halprofile_100.jpg'

    ############################################################################
    # cookie
    ############################################################################

    session.lifetime: '+20 minutes'
    session.encryption.secret: ''

    cookie.encryption.secret: ''
    # session.cookie.configuration:
    #     lifetime: '5 days'
    # cookie.preferences.ttl: '5 years'

    ############################################################################
    # permission settings
    ############################################################################

    # Check GitHub collaborators for non-prod permissions
    permissions.check.github: true

    ############################################################################
    # agent
    ############################################################################

    hal.agents: []

    ############################################################################
    # crypto
    ############################################################################

    encrypter.hal.secret.path: 'configuration/hal.encrypter.secret'
