imports:
    - resource: ../vendor/ql/hal-core/configuration/hal-core.yml
    - resource: ../vendor/ql/panthor/configuration/di.yml
    - resource: di.yml
    - resource: config.global.yml
    - resource: config.env.yml
    - resource: routes.yml
    - resource: kraken/kraken.yml

parameters:
    # environment independent parameters
    application.id: '200947'
    application.major.version: '2'

    # Replaced before di compiling
    application.sha: ''
    session.encryption.secret: %encryption.secret%

    slim.hooks:
        slim.before:
            - 'slim.hook.logger'
            - 'slim.hook.errors'
        slim.before.router:
            - 'app.slim.hook.routes'
