imports:
    - resource: '../vendor/ql/mcp-panthor/configuration/panthor-slim.yml'
    - resource: '../vendor/ql/mcp-panthor/configuration/panthor.yml'

    - resource: 'di.yml'
    - resource: 'di/services.yml'

    - resource: 'ui/controllers.yml'
    - resource: 'ui/middleware.yml'
    - resource: 'ui/services.yml'
    - resource: 'ui/routes.yml'

    - resource: 'api/controllers.yml'
    - resource: 'api/middleware.yml'
    - resource: 'api/services.yml'
    - resource: 'api/routes.yml'

    - resource: 'api-internal/controllers.yml'
    - resource: 'api-internal/routes.yml'

    - resource: 'config.global.yml'
    - resource: 'config.env.yml'

parameters:
    # environment independent parameters
    application.id: '200947'

    application.major.version: '3'
    application.minor.version: '0'
    application.version: '%application.major.version%.%application.minor.version%'

    # Replaced before di compiling
    application.sha: ''

    global_middleware:
        - 'slim.global_middleware.logger'
        - 'slim.global_middleware.template_context'
        - 'panthor.middleware.encrypted_cookies'
        - 'slim.global_middleware.flash'
        - 'slim.global_middleware.session'
        - 'slim.global_middleware.user_session'
        - 'slim.global_middleware.srs_business'


    # Route condition regexes

    # use these
    r.alphanum: '[A-Za-z0-9]+'
    r.digit: '[0-9]+'
    r.guid: '[0-9a-zA-Z]{32,32}'
    r.build: '[A-Za-z0-9\_\-\.]+'
    r.release: '%r.build%'
    r.date: '[0-9]{4}-[0-9]{2}-[0-9]{2}'

    r.api.queue: '[A-Za-z0-9\+\-\.]+'

    # not these (deprecated)
    routes.regex.alphanum: '%r.alphanum%'
    routes.regex.digit: '%r.digit%'
    routes.regex.guid: '%r.guid%'

    routes.regex.buildId: '%r.build%'
    routes.regex.pushId: '%r.release%'

    routes.regex.date: '%r.date%'
