imports:
    - resource: ../vendor/ql/hal-core/configuration/hal-core.yml
    - resource: ../vendor/ql/kraken-core/configuration/kraken-core.yml
    - resource: ../vendor/ql/mcp-panthor/configuration/panthor.yml
    - resource: ../vendor/ql/panthor-plugins/configuration/panthor-plugins.yml
    - resource: di.yml
    - resource: config.global.yml
    - resource: config.env.yml
    - resource: routes.yml
    - resource: kraken/kraken.yml

parameters:
    # environment independent parameters
    application.id: '200947'
    application.major.version: '2'

    # Replaced before di compiling
    application.sha: ''

    slim.hooks:
        slim.before:
            - 'panthor.plugin.logging.hook'
        slim.before.router:
            - 'app.slim.hook.routes'
