imports:
    - resource: routes/routes.admin.yml
    - resource: routes/routes.api.yml
    - resource: routes/routes.application.yml
    - resource: routes/routes.yml

parameters:
    routes.regex.alphanum: '[A-Za-z0-9]+'
    routes.regex.digit: '[0-9]+'
    routes.regex.guid: '[0-9a-zA-Z]{32,32}'

    routes.regex.buildId: '[A-Za-z0-9\_\-\.]+'
    routes.regex.pushId: %routes.regex.buildId%
