services:
    index.api:
        public: true
        class: 'Hal\UI\Controllers\API\IndexController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'

    docs.api:
        public: true
        class: 'Hal\UI\Controllers\API\DocsRedirectController'
        arguments:
            - '@QL\Panthor\Utility\URI'

    ####################################################################################################################
    # QUEUE CONTROLLERS
    ####################################################################################################################

    queue.api:
        public: true
        class: 'Hal\UI\Controllers\API\Queue\QueueController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\BuildNormalizer'
            - '@Hal\UI\API\Normalizer\ReleaseNormalizer'
            - '@Hal\UI\Service\JobQueueService'
            - '@QL\Panthor\HTTPProblem\ProblemRendererInterface'
            - '@QL\MCP\Common\Clock'

    queue.refresh.api:
        public: true
        class: 'Hal\UI\Controllers\API\Queue\QueueRefreshController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\BuildNormalizer'
            - '@Hal\UI\API\Normalizer\ReleaseNormalizer'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@QL\Panthor\HTTPProblem\ProblemRendererInterface'

    queue.history.api:
        public: true
        class: 'Hal\UI\Controllers\API\Queue\QueueHistoryController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\BuildNormalizer'
            - '@Hal\UI\API\Normalizer\ReleaseNormalizer'
            - '@Hal\UI\Service\JobQueueService'
            - '@QL\MCP\Common\Clock'
            - '%date.timezone%'

    ####################################################################################################################
    # ORGANIZATION CONTROLLERS
    ####################################################################################################################

    organization.api:
        public: true
        class: 'Hal\UI\Controllers\API\Organization\OrganizationController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\OrganizationNormalizer'

    organizations.api:
        public: true
        class: 'Hal\UI\Controllers\API\Organization\OrganizationsController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Hal\UI\API\Normalizer\OrganizationNormalizer'

    ####################################################################################################################
    # APPLICATION CONTROLLERS
    ####################################################################################################################

    application.api:
        public: true
        class: 'Hal\UI\Controllers\API\Application\ApplicationController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\ApplicationNormalizer'

    applications.api:
        public: true
        class: 'Hal\UI\Controllers\API\Application\ApplicationsController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@QL\Panthor\HTTPProblem\ProblemRendererInterface'

    ####################################################################################################################
    # TEMPLATE CONTROLLERS
    ####################################################################################################################

    templates.api:
        public: true
        class: 'Hal\UI\Controllers\API\Template\TemplatesController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@QL\Panthor\HTTPProblem\ProblemRendererInterface'

    template.api:
        public: true
        class: 'Hal\UI\Controllers\API\Template\TemplateController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\TemplateNormalizer'

    ####################################################################################################################
    # TARGET CONTROLLERS
    ####################################################################################################################

    target.api:
        public: true
        class: 'Hal\UI\Controllers\API\Target\TargetController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\TargetNormalizer'

    targets.api:
        public: true
        class: 'Hal\UI\Controllers\API\Target\TargetsController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Doctrine\ORM\EntityManagerInterface'

    target.history.api:
        public: true
        class: 'Hal\UI\Controllers\API\Target\HistoryController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@QL\Panthor\HTTPProblem\ProblemRendererInterface'

    target.current_release.api:
        public: true
        class: 'Hal\UI\Controllers\API\Target\CurrentReleaseController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\ReleaseNormalizer'
            - '@QL\Panthor\HTTPProblem\ProblemRendererInterface'

    ####################################################################################################################
    # BUILD CONTROLLERS
    ####################################################################################################################

    build.api:
        public: true
        class: 'Hal\UI\Controllers\API\Build\BuildController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\BuildNormalizer'

    build.events.api:
        public: true
        class: 'Hal\UI\Controllers\API\Build\EventsController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\Service\JobEventsService'

    builds.api:
        public: true
        class: 'Hal\UI\Controllers\API\Build\BuildsController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@QL\Panthor\HTTPProblem\ProblemRendererInterface'

    builds.history.api:
        public: true
        class: 'Hal\UI\Controllers\API\Queue\BuildsHistoryController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@QL\Panthor\HTTPProblem\ProblemRendererInterface'

    ####################################################################################################################
    # Release CONTROLLERS
    ####################################################################################################################

    release.api:
        public: true
        class: 'Hal\UI\Controllers\API\Release\ReleaseController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\ReleaseNormalizer'

    release.events.api:
        public: true
        class: 'Hal\UI\Controllers\API\Release\EventsController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\Service\JobEventsService'

    releases.api:
        public: true
        class: 'Hal\UI\Controllers\API\Release\ReleasesController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@QL\Panthor\HTTPProblem\ProblemRendererInterface'

    releases.history.api:
        public: true
        class: 'Hal\UI\Controllers\API\Queue\ReleasesHistoryController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@QL\Panthor\HTTPProblem\ProblemRendererInterface'

    ####################################################################################################################
    # EVENT CONTROLLERS
    ####################################################################################################################

    event.api:
        public: true
        class: 'Hal\UI\Controllers\API\EventController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\EventNormalizer'

    ####################################################################################################################
    # ENVIRONMENTS CONTROLLERS
    ####################################################################################################################

    environments.api:
        public: true
        class: 'Hal\UI\Controllers\API\Environment\EnvironmentsController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Hal\UI\API\Normalizer\EnvironmentNormalizer'

    environment.api:
        public: true
        class: 'Hal\UI\Controllers\API\Environment\EnvironmentController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\EnvironmentNormalizer'

    ####################################################################################################################
    # VERSION CONTROL PROVIDER CONTROLLERS
    ####################################################################################################################

    vcs_providers.api:
        public: true
        class: 'Hal\UI\Controllers\API\VersionControl\VersionControlProvidersController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@QL\Panthor\HTTPProblem\ProblemRendererInterface'

    vcs_provider.api:
        public: true
        class: 'Hal\UI\Controllers\API\VersionControl\VersionControlProviderController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\VersionControlProviderNormalizer'

    ####################################################################################################################
    # USER CONTROLLERS
    ####################################################################################################################

    user.api:
        public: true
        class: 'Hal\UI\Controllers\API\User\UserController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Hal\UI\API\Normalizer\UserNormalizer'
    users.api:
        public: true
        class: 'Hal\UI\Controllers\API\User\UsersController'
        arguments:
            - '@Hal\UI\API\ResponseFormatter'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@QL\Panthor\HTTPProblem\ProblemRendererInterface'
