services:
    index.api:
        class: 'Hal\UI\Controllers\API\IndexController'
        arguments: ['@api.response_formatter']

    docs.api:
        class: 'Hal\UI\Controllers\API\DocsRedirectController'
        arguments: ['@uri']

    ####################################################################################################################
    # QUEUE CONTROLLERS
    ####################################################################################################################

    queue.api:
        class: 'Hal\UI\Controllers\API\Queue\QueueController'
        arguments:
            - '@api.response_formatter'
            - '@api_normalizer.build'
            - '@api_normalizer.release'
            - '@job_queue'
            - '@problem.renderer'
            - '@clock'

    queue.refresh.api:
        class: 'Hal\UI\Controllers\API\Queue\QueueRefreshController'
        arguments:
            - '@api.response_formatter'
            - '@api_normalizer.build'
            - '@api_normalizer.release'
            - '@doctrine.em'
            - '@problem.renderer'

    queue.history.api:
        class: 'Hal\UI\Controllers\API\Queue\QueueHistoryController'
        arguments:
            - '@api.response_formatter'
            - '@api_normalizer.build'
            - '@api_normalizer.release'
            - '@job_queue'
            - '@clock'
            - '%date.timezone%'

    ####################################################################################################################
    # ORGANIZATION CONTROLLERS
    ####################################################################################################################

    organization.api:
        class: 'Hal\UI\Controllers\API\Organization\OrganizationController'
        arguments: ['@api.response_formatter', '@api_normalizer.organization']

    organizations.api:
        class: 'Hal\UI\Controllers\API\Organization\OrganizationsController'
        arguments:
            - '@api.response_formatter'
            - '@doctrine.em'
            - '@api_normalizer.organization'

    ####################################################################################################################
    # APPLICATION CONTROLLERS
    ####################################################################################################################

    application.api:
        class: 'Hal\UI\Controllers\API\Application\ApplicationController'
        arguments: ['@api.response_formatter', '@api_normalizer.application']

    applications.api:
        class: 'Hal\UI\Controllers\API\Application\ApplicationsController'
        arguments:
            - '@api.response_formatter'
            - '@doctrine.em'
            - '@problem.renderer'

    ####################################################################################################################
    # TEMPLATE CONTROLLERS
    ####################################################################################################################

    templates.api:
        class: 'Hal\UI\Controllers\API\Template\TemplatesController'
        arguments:
            - '@api.response_formatter'
            - '@doctrine.em'
            - '@problem.renderer'

    template.api:
        class: 'Hal\UI\Controllers\API\Template\TemplateController'
        arguments: ['@api.response_formatter', '@api_normalizer.template']

    ####################################################################################################################
    # TARGET CONTROLLERS
    ####################################################################################################################

    target.api:
        class: 'Hal\UI\Controllers\API\Target\TargetController'
        arguments: ['@api.response_formatter', '@api_normalizer.target']

    targets.api:
        class: 'Hal\UI\Controllers\API\Target\TargetsController'
        arguments: ['@api.response_formatter', '@doctrine.em']

    target.history.api:
        class: 'Hal\UI\Controllers\API\Target\HistoryController'
        arguments:
            - '@api.response_formatter'
            - '@doctrine.em'
            - '@problem.renderer'

    target.current_release.api:
        class: 'Hal\UI\Controllers\API\Target\CurrentReleaseController'
        arguments:
            - '@api.response_formatter'
            - '@api_normalizer.release'
            - '@problem.renderer'

    ####################################################################################################################
    # BUILD CONTROLLERS
    ####################################################################################################################

    build.api:
        class: 'Hal\UI\Controllers\API\Build\BuildController'
        arguments: ['@api.response_formatter', '@api_normalizer.build']

    build.events.api:
        class: 'Hal\UI\Controllers\API\Build\EventsController'
        arguments: ['@api.response_formatter', '@service.event_logs']

    builds.api:
        class: 'Hal\UI\Controllers\API\Build\BuildsController'
        arguments:
            - '@api.response_formatter'
            - '@doctrine.em'
            - '@problem.renderer'

    builds.history.api:
        class: 'Hal\UI\Controllers\API\Queue\BuildsHistoryController'
        arguments:
            - '@api.response_formatter'
            - '@doctrine.em'
            - '@problem.renderer'

    ####################################################################################################################
    # Release CONTROLLERS
    ####################################################################################################################

    release.api:
        class: 'Hal\UI\Controllers\API\Release\ReleaseController'
        arguments: ['@api.response_formatter', '@api_normalizer.release']

    release.events.api:
        class: 'Hal\UI\Controllers\API\Release\EventsController'
        arguments: ['@api.response_formatter', '@service.event_logs']

    releases.api:
        class: 'Hal\UI\Controllers\API\Release\ReleasesController'
        arguments:
            - '@api.response_formatter'
            - '@doctrine.em'
            - '@problem.renderer'

    releases.history.api:
        class: 'Hal\UI\Controllers\API\Queue\ReleasesHistoryController'
        arguments:
            - '@api.response_formatter'
            - '@doctrine.em'
            - '@problem.renderer'

    ####################################################################################################################
    # EVENT CONTROLLERS
    ####################################################################################################################

    event.api:
        class: 'Hal\UI\Controllers\API\EventController'
        arguments: ['@api.response_formatter', '@api_normalizer.event']

    ####################################################################################################################
    # ENVIRONMENTS CONTROLLERS
    ####################################################################################################################

    environments.api:
        class: 'Hal\UI\Controllers\API\Environment\EnvironmentsController'
        arguments:
            - '@api.response_formatter'
            - '@doctrine.em'
            - '@api_normalizer.environment'

    environment.api:
        class: 'Hal\UI\Controllers\API\Environment\EnvironmentController'
        arguments: ['@api.response_formatter', '@api_normalizer.environment']

    ####################################################################################################################
    # USER CONTROLLERS
    ####################################################################################################################

    user.api:
        class: 'Hal\UI\Controllers\API\User\UserController'
        arguments: ['@api.response_formatter', '@api_normalizer.user']
    users.api:
        class: 'Hal\UI\Controllers\API\User\UsersController'
        arguments:
            - '@api.response_formatter'
            - '@doctrine.em'
            - '@problem.renderer'
