services:
    middleware.api_caching:
        class: 'Hal\UI\Middleware\APICachingMiddleware'
        arguments: ['@api.response_formatter']

    middleware.api_require_entity:
        class: 'Hal\UI\Middleware\RequireEntityMiddleware'
        arguments: ['@doctrine.em', '@notFoundHandler']

    middleware.api_cross_origin:
        class: 'Hal\UI\Middleware\APICrossOriginMiddleware'
