services:
    middleware.api_caching:
        class: 'Hal\UI\Middleware\APICachingMiddleware'
        arguments: ['@api.response_formatter']

    middleware.api_require_entity:
        class: 'Hal\UI\Middleware\RequireEntityMiddleware'
        arguments: ['@doctrine.em', '@notFoundHandler']

    middleware.api_cross_origin:
        class: 'Hal\UI\Middleware\APICrossOriginMiddleware'
        arguments: ['@middleware.api_cross_origin.analyzer_settings', '@problem.renderer']

    middleware.api_cross_origin.analyzer_settings:
        class: 'Neomerx\Cors\Strategies\Settings'
        calls:
            - ['setRequestCredentialsSupported', [true]]
            - ['setRequestAllowedHeaders', ['%api.cors.allowed_headers%']]
            - ['setRequestAllowedOrigins', ['%api.cors.allowed_origins%']]
