parameters:
    routes.api:

        api.docs:
            route: '/docs/api'
            stack: ['docs.api']

        api.index:
            method: 'GET'
            route: '/api'
            stack: ['index.api']

        api:
            route: '/api'
            stack: ['middleware.api_caching']
            routes:

                ################################################################################################################
                # QUEUE ROUTES
                ################################################################################################################

                api.queue:
                    method: 'GET'
                    route: '/queue'
                    stack: ['queue.api']

                api.queue.refresh:
                    method: 'GET'
                    route: '/queue-refresh/{jobs:%r.api.queue%}'
                    stack: ['queue.refresh.api']

                api.queue.history:
                    method: 'GET'
                    route: '/queue/date/{date:%r.date%}'
                    stack: ['queue.history.api']

                ################################################################################################################
                # ORGANIZATION ROUTES
                ################################################################################################################

                api.organizations:
                    method: 'GET'
                    route: '/organizations'
                    stack: ['organizations.api']

                api.organization:
                    method: 'GET'
                    route: '/organizations/{organization:%r.guid%}'
                    stack: ['middleware.api_require_entity', 'organization.api']

                ################################################################################################################
                # APPLICATION ROUTES
                ################################################################################################################

                api.applications:
                    method: 'GET'
                    route: '/applications'
                    stack: ['applications.api']
                api.applications.paged:
                    method: 'GET'
                    route: '/applications/page/{page:%r.digit%}'
                    stack: ['applications.api']

                api.application.management:
                    route: '/applications/{application:%r.guid%}'
                    stack: ['middleware.api_require_entity']
                    routes:

                        api.application:
                            method: 'GET'
                            route: ''
                            stack: ['application.api']

                        api.targets:
                            method: 'GET'
                            route: '/targets'
                            stack: ['targets.api']

                        # are these application routes or build/push routes?
                        # It's nice to be able to use route groups to nest common url prefixes.

                        api.builds:
                            method: 'GET'
                            route: '/builds'
                            stack: ['builds.api']
                        api.builds.history:
                            method: 'GET'
                            route: '/builds/page/{page:%r.digit%}'
                            stack: ['builds.api']

                        api.releases:
                            method: 'GET'
                            route: '/releases'
                            stack: ['releases.api']
                        api.releases.history:
                            method: 'GET'
                            route: '/releases/page/{page:%r.digit%}'
                            stack: ['releases.api']

                ################################################################################################################
                # GROUP ROUTES
                ################################################################################################################

                api.groups:
                    method: 'GET'
                    route: '/groups'
                    stack: ['groups.api']

                api.groups.paged:
                    method: 'GET'
                    route: '/groups/page/{page:%r.digit%}'
                    stack: ['groups.api']

                api.group:
                    method: 'GET'
                    route: '/groups/{group:%r.guid%}'
                    stack: ['middleware.api_require_entity', 'group.api']

                ################################################################################################################
                # TARGET ROUTES
                ################################################################################################################

                api.target.management:
                    route: '/targets/{target:%r.guid%}'
                    stack: ['middleware.api_require_entity']
                    routes:
                        api.target:
                            method: 'GET'
                            route: ''
                            stack: ['target.api']

                        api.target.history:
                            method: 'GET'
                            route: '/releases'
                            stack: ['target.history.api']
                        api.target.history.paged:
                            method: 'GET'
                            route: '/releases/page/{page:%r.digit%}'
                            stack: ['target.history.api']

                        api.target.current_release:
                            method: 'GET'
                            route: '/current-release'
                            stack: ['target.current_release.api']

                ################################################################################################################
                # BUILD ROUTES
                ################################################################################################################

                api.build:
                    method: 'GET'
                    route: '/builds/{build:%r.build%}'
                    stack: ['middleware.api_require_entity', 'build.api']

                api.build.events:
                    method: 'GET'
                    route: '/builds/{build:%r.build%}/events'
                    stack: ['middleware.api_require_entity', 'build.events.api']

                api.build.list:
                    method: 'GET'
                    route: '/builds'
                    stack: ['middleware.api_require_entity', 'builds.list.api']

                api.build.list.paged:
                    method: 'GET'
                    route: '/builds/page/{page:%r.digit%}'
                    stack: ['middleware.api_require_entity', 'builds.list.api']

                ################################################################################################################
                # RELEASE ROUTES
                ################################################################################################################

                api.release:
                    method: 'GET'
                    route: '/releases/{release:%r.release%}'
                    stack: ['middleware.api_require_entity', 'release.api']

                api.release.events:
                    method: 'GET'
                    route: '/releases/{release:%r.release%}/events'
                    stack: ['middleware.api_require_entity', 'release.events.api']

                api.release.list:
                    method: 'GET'
                    route: '/releases'
                    stack: ['middleware.api_require_entity', 'releases.list.api']

                api.release.list.paged:
                    method: 'GET'
                    route: '/releases/page/{page:%r.digit%}'
                    stack: ['middleware.api_require_entity', 'releases.list.api']

                ################################################################################################################
                # EVENT ROUTES
                ################################################################################################################

                api.event:
                    method: 'GET'
                    route: '/job-events/{event:%r.guid%}'
                    stack: ['middleware.api_require_entity', 'event.api']

                ################################################################################################################
                # ENVIRONMENTS ROUTES
                ################################################################################################################

                api.environments:
                    method: 'GET'
                    route: '/environments'
                    stack: ['environments.api']

                api.environment:
                    method: 'GET'
                    route: '/environments/{environment:%r.guid%}'
                    stack: ['middleware.api_require_entity', 'environment.api']

                ################################################################################################################
                # USER ROUTES
                ################################################################################################################

                api.users:
                    method: 'GET'
                    route: '/users'
                    stack: ['users.api']
                api.users.paged:
                    method: 'GET'
                    route: '/users/page/{page:%r.digit%}'
                    stack: ['users.api']

                api.user:
                    method: 'GET'
                    route: '/users/{user:%r.guid%}'
                    stack: ['middleware.api_require_entity', 'user.api']

