services:

    api.cache:
        class: 'QL\MCP\Cache\CacheInterface'
        factory: ['@service_container', 'get']
        arguments: ['cache.%cache.type.api%']

    api.response_formatter:
        class: 'Hal\UI\API\ResponseFormatter'
        arguments: ['@api.normalizer', '@uri']
        calls:
            - ['setCache', ['@api.cache']]
            - ['setCacheTimes', ['%api.cachetimes%']]

    api.normalizer:
        class: 'Hal\UI\API\Normalizer'
        calls:
            - ['addNormalizer', ['Hal\Core\Entity\Application', '@api_normalizer.application']]
            - ['addNormalizer', ['Hal\Core\Entity\Target', '@api_normalizer.target']]
            - ['addNormalizer', ['Hal\Core\Entity\Environment', '@api_normalizer.environment']]
            - ['addNormalizer', ['Hal\Core\Entity\Organization', '@api_normalizer.organization']]
            - ['addNormalizer', ['Hal\Core\Entity\JobType\Build', '@api_normalizer.build']]
            - ['addNormalizer', ['Hal\Core\Entity\JobType\Release', '@api_normalizer.release']]
            - ['addNormalizer', ['Hal\Core\Entity\Job\JobEvent', '@api_normalizer.event']]
            # - ['addNormalizer', ['Hal\Core\Entity\Group', '@api_normalizer.group']]
            - ['addNormalizer', ['Hal\Core\Entity\User', '@api_normalizer.user']]
            - ['addNormalizer', ['Hal\Core\Entity\System\VersionControlProvider', '@api_normalizer.vcs_provider']]
            - ['addNormalizer', ['QL\MCP\Common\Time\TimePoint', '@api_normalizer.timepoint']]
            - ['addNormalizer', ['Hal\UI\API\Hyperlink', '@api_normalizer.hyperlink']]

    ####################################################################################################################
    # API Entity Normalizers
    ####################################################################################################################

    api_normalizer.build:
        class: 'Hal\UI\API\Normalizer\BuildNormalizer'
        arguments:
            - '@vcs'
            - '@api_normalizer.environment'

    api_normalizer.target:
        class: 'Hal\UI\API\Normalizer\TargetNormalizer'

    api_normalizer.environment:
        class: 'Hal\UI\API\Normalizer\EnvironmentNormalizer'

    api_normalizer.event:
        class: 'Hal\UI\API\Normalizer\EventNormalizer'

    api_normalizer.organization:
        class: 'Hal\UI\API\Normalizer\OrganizationNormalizer'

    api_normalizer.release:
        class: 'Hal\UI\API\Normalizer\ReleaseNormalizer'

    api_normalizer.application:
        class: 'Hal\UI\API\Normalizer\ApplicationNormalizer'
        arguments: ['@vcs']

    api_normalizer.group:
        class: 'Hal\UI\API\Normalizer\GroupNormalizer'
        arguments: ['@doctrine.em']

    api_normalizer.timepoint:
        class: 'Hal\UI\API\Normalizer\TimePointNormalizer'

    api_normalizer.user:
        class: 'Hal\UI\API\Normalizer\UserNormalizer'
        arguments: ['@service.authorization']

    api_normalizer.vcs_provider:
        class: 'Hal\UI\API\Normalizer\VersionControlProviderNormalizer'

    api_normalizer.hyperlink:
        class: 'Hal\UI\API\Normalizer\HyperlinkNormalizer'
        arguments: ['@uri', '@request']
